/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'index.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.android-arm64.node')
          } else {
            nativeBinding = require('@a3s-lab/code-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'index.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.android-arm-eabi.node')
          } else {
            nativeBinding = require('@a3s-lab/code-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@a3s-lab/code-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@a3s-lab/code-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@a3s-lab/code-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'index.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./index.darwin-universal.node')
      } else {
        nativeBinding = require('@a3s-lab/code-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'index.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.darwin-x64.node')
          } else {
            nativeBinding = require('@a3s-lab/code-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'index.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.darwin-arm64.node')
          } else {
            nativeBinding = require('@a3s-lab/code-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'index.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./index.freebsd-x64.node')
      } else {
        nativeBinding = require('@a3s-lab/code-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-x64-musl.node')
            } else {
              nativeBinding = require('@a3s-lab/code-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@a3s-lab/code-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@a3s-lab/code-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@a3s-lab/code-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@a3s-lab/code-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@a3s-lab/code-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@a3s-lab/code-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@a3s-lab/code-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'index.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@a3s-lab/code-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { StateGraphRuntime, EventStream, FileMemoryStore, FileSessionStore, MemorySessionStore, DefaultSecurityProvider, LocalWorkspaceBackend, S3WorkspaceBackend, BrowserBackend, Session, WorkspaceRetrievalOptions, CallbackEmbeddingProvider, DeterministicWorkspaceReranker, Agent, ServeHandle, formatVerificationSummary, agentEventTypesV1, eventEnvelopeV1Version, builtinSkills } = nativeBinding

module.exports.StateGraphRuntime = StateGraphRuntime
module.exports.EventStream = EventStream
module.exports.FileMemoryStore = FileMemoryStore
module.exports.FileSessionStore = FileSessionStore
module.exports.MemorySessionStore = MemorySessionStore
module.exports.DefaultSecurityProvider = DefaultSecurityProvider
module.exports.LocalWorkspaceBackend = LocalWorkspaceBackend
module.exports.S3WorkspaceBackend = S3WorkspaceBackend
module.exports.BrowserBackend = BrowserBackend
module.exports.Session = Session
module.exports.WorkspaceRetrievalOptions = WorkspaceRetrievalOptions
module.exports.CallbackEmbeddingProvider = CallbackEmbeddingProvider
module.exports.DeterministicWorkspaceReranker = DeterministicWorkspaceReranker
module.exports.Agent = Agent
module.exports.ServeHandle = ServeHandle

// a3s-code: EventStream async iterator bridge
// napi-rs exposes the async `next()` method but does not install the symbol
// required by JavaScript's `for await ... of` protocol.
if (EventStream && typeof EventStream.prototype[Symbol.asyncIterator] !== 'function') {
  Object.defineProperty(EventStream.prototype, Symbol.asyncIterator, {
    configurable: true,
    value: function asyncIterator() {
      return this
    },
  })
}


// a3s-code: typed core error bridge
// Core errors carry a private marker across napi's generic Error conversion.
// Strip it at the JS boundary and expose the stable machine-readable code.
function normalizeA3sCodeError(error) {
  if (!(error instanceof Error)) return error
  const match = /^\[A3S_CODE_ERROR:([A-Z_]+)\]\s*/.exec(error.message)
  if (!match) return error
  Object.defineProperty(error, 'code', {
    configurable: true,
    enumerable: true,
    value: match[1],
  })
  error.message = error.message.slice(match[0].length)
  return error
}

function wrapA3sCodeErrors(target, methods) {
  if (!target) return
  for (const method of methods) {
    const original = target[method]
    if (typeof original !== 'function' || original.__a3sTypedErrorBridge) continue
    const wrapped = function typedErrorBridge(...args) {
      try {
        const result = original.apply(this, args)
        if (result && typeof result.then === 'function') {
          return result.catch((error) => { throw normalizeA3sCodeError(error) })
        }
        return result
      } catch (error) {
        throw normalizeA3sCodeError(error)
      }
    }
    Object.defineProperty(wrapped, '__a3sTypedErrorBridge', { value: true })
    target[method] = wrapped
  }
}

wrapA3sCodeErrors(Agent, ['create'])
wrapA3sCodeErrors(Agent && Agent.prototype, [
  'session', 'sessionAsync', 'resumeSession', 'resumeSessionAsync',
  'sessionForAgent', 'sessionForAgentAsync', 'sessionForWorker',
  'sessionForWorkerAsync', 'refreshMcpTools',
])
wrapA3sCodeErrors(Session && Session.prototype, [
  'send', 'run', 'resumeRun', 'sendRequest', 'stream', 'streamRequest',
  'sendWithAttachments', 'streamWithAttachments', 'save',
  'addMcpServer', 'addMcpServerConfig', 'addMcp', 'removeMcpServer', 'removeMcp',
  'tool', 'task', 'delegateTask', 'tasks', 'parallelTask', 'program',
  'readFile', 'writeFile', 'ls', 'editFile', 'patchFile', 'bash', 'glob', 'grep',
  'webSearch', 'git', 'gitCommand', 'confirmToolUse', 'verifyCommands',
  'registerAgentDir', 'registerWorkerAgent', 'registerWorkerAgents',
  'registerDynamicWorkflowRuntime', 'unregisterDynamicTool',
  'registerHook', 'unregisterHook', 'registerCommand',
])

module.exports.formatVerificationSummary = formatVerificationSummary
module.exports.agentEventTypesV1 = agentEventTypesV1
module.exports.eventEnvelopeV1Version = eventEnvelopeV1Version
module.exports.builtinSkills = builtinSkills
