/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Unique task identifier (UUID string in JavaScript). */
export interface TaskId {
  /** The task ID as a string */
  id: string
}
/** Task execution status. */
export interface TaskStatus {
  /** Status string: "pending", "running", "completed", "failed", "killed" */
  status: string
}
/** Task type variants. */
export interface TaskType {
  /** Type string: "tool", "agent", "remote_agent", "in_process_teammate", "workflow", "coordinator", "monitor_mcp", "idle" */
  type: string
  /** JSON-encoded data for the variant */
  data?: string
}
/** Base task with lifecycle management. */
export interface Task {
  id: string
  kind: TaskType
  status: TaskStatus
  description: string
  toolUseId?: string
  parentId?: string
  childIds: Array<string>
  error?: string
}
/** Result of a completed task. */
export interface TaskResult {
  taskId: string
  output?: string
  durationMs: number
}
/** Token usage statistics for a task. */
export interface TaskTokenUsage {
  inputTokens: number
  outputTokens: number
  cacheReadTokens: number
  cacheWriteTokens: number
}
/** Record of a single tool activity. */
export interface ToolActivity {
  toolName: string
  timestamp: string
  argsSummary: string
  success: boolean
}
/** Snapshot of agent execution progress. */
export interface AgentProgress {
  toolCounts: Record<string, number>
  totalToolCalls: number
  tokenUsage: TaskTokenUsage
  recentActivities: Array<ToolActivity>
  elapsedMs: number
  running: boolean
}
/** Phase of an idle task. */
export interface IdlePhase {
  /** Phase string: "starting", "consolidating", "updating", "completed" */
  phase: string
}
/** Tool call recorded during an idle turn. */
export interface IdleToolCall {
  name: string
  argsSummary: string
  success: boolean
}
/** A single turn in idle execution. */
export interface IdleTurn {
  text: string
  toolCalls: Array<IdleToolCall>
  touchedFiles: Array<string>
  inputTokens: number
  outputTokens: number
}
/** Memory update produced by idle completion. */
export interface MemoryUpdate {
  semanticFacts: Array<string>
  episodicEntries: Array<EpisodicEntry>
  proceduralUpdates: Array<string>
  totalTokens: number
  durationMs: number
}
/** Episodic memory entry from idle. */
export interface EpisodicEntry {
  timestamp: string
  description: string
  relatedFiles: Array<string>
  importance: number
}
/** Idle (memory consolidation) task state. */
export interface IdleTask {
  id: string
  phase: IdlePhase
  reason: string
  turns: Array<IdleTurn>
  touchedFiles: Array<string>
  error?: string
}
/** AHP event type. */
export interface AhpEventType {
  /** Event type string: "handshake", "pre_action", "post_action", "pre_prompt", "post_response", "session_start", "session_end", "error", "query", "heartbeat", "idle" */
  eventType: string
}
/** A factual memory item. */
export interface AhpFact {
  content: string
  source: string
  confidence: number
}
/** Memory state summary. */
export interface AhpMemorySummary {
  memoryType: string
  totalItems: number
  recentTopics: Array<string>
}
/** Session statistics. */
export interface AhpSessionStats {
  totalActions: number
  totalTokens: number
  durationMs: number
  errorCount: number
}
/** Decision from harness for idle events. */
export interface AhpIdleDecision {
  /** Decision string: "allow" or "defer" */
  decision: string
  /** Reason if deferred */
  reason?: string
}
/** Context passed with AHP events. */
export interface AhpEventContext {
  recentFacts?: Array<AhpFact>
  memorySummary?: AhpMemorySummary
  sessionStats?: AhpSessionStats
  currentTask?: string
  capabilities?: Record<string, string>
}
export interface AgentResult {
  text: string
  toolCallsCount: number
  promptTokens: number
  completionTokens: number
  totalTokens: number
}
/**
 * Result of a `/btw` ephemeral side question.
 *
 * The answer is never added to conversation history.
 */
export interface BtwResult {
  /** The original question. */
  question: string
  /** The LLM's answer. */
  answer: string
  /** Token usage for this ephemeral call. */
  promptTokens: number
  completionTokens: number
  totalTokens: number
}
export interface AgentEvent {
  type: string
  text?: string
  toolName?: string
  toolId?: string
  toolOutput?: string
  exitCode?: number
  turn?: number
  prompt?: string
  error?: string
  totalTokens?: number
  /** For btw_answer event: the original question */
  question?: string
  /** For btw_answer event: the LLM's answer */
  answer?: string
  /** Extra data for events that don't map to standard fields (JSON-encoded) */
  data?: string
}
export interface ToolResult {
  name: string
  output: string
  exitCode: number
  /** Raw JSON-encoded tool metadata returned by the Rust core API. */
  metadataJson?: string
  /** Convenience JSON view of `metadata.document_runtime` when present. */
  documentRuntimeJson?: string
}
/** Parameters for the web_search tool. */
export interface JsWebSearchParams {
  /** The search query. */
  query: string
  /** List of search engines to use. */
  engines?: Array<string>
  /** Maximum number of results to return (default: 10, max: 50). */
  limit?: number
  /** Search timeout in seconds (default: 10, max: 60). */
  timeout?: number
  /** Proxy URL (e.g., http://127.0.0.1:8080 or socks5://127.0.0.1:1080). */
  proxy?: string
  /** Output format: "text" or "json". */
  format?: string
}
/** Result of a single `EventStream.next()` call. */
export interface NextResult {
  value?: AgentEvent
  done: boolean
}
/**
 * An inline skill registered programmatically (no file required).
 *
 * Use `kind: "instruction"` for prompt injections or `kind: "persona"` to
 * replace the default role section of the system prompt.
 */
export interface InlineSkill {
  /** Unique skill name (kebab-case recommended, e.g. "type-hints"). */
  name: string
  /** Skill kind: `"instruction"` or `"persona"`. */
  kind: string
  /** Markdown content for the skill. */
  content: string
}
export interface JsMemoryStore {
  backend: string
  dir?: string
}
export interface JsSessionStore {
  backend: string
  dir?: string
}
export interface JsSecurityProvider {
  kind: string
}
/**
 * A plugin descriptor passed in `SessionOptions.plugins`.
 *
 * Use `new SkillPlugin(...)` to create plugin instances — do not construct
 * this object directly.
 */
export interface JsPlugin {
  /** Plugin kind: currently only `"skill_plugin"`. */
  kind: string
  /** Plugin name (used by SkillPlugin). */
  pluginName?: string
  /** Skill YAML/markdown content strings (used by SkillPlugin). */
  skills?: Array<string>
}
/**
 * Union type for AHP transport configuration.
 * Accepts any of: StdioTransport, HttpTransport, WebSocketTransport, UnixSocketTransport.
 */
export interface JsAhpTransport {
  kind: string
  program?: string
  args?: Array<string>
  url?: string
  authToken?: string
  path?: string
}
export interface SessionOptions {
  /** Override the default model. Format: "provider/model" (e.g., "openai/gpt-4o"). */
  model?: string
  /** Enable built-in skills (7 skills: code-search, code-review, explain-code, find-bugs, builtin-tools, delegate-task, find-skills). */
  builtinSkills?: boolean
  /** Extra directories to scan for skill files (.md with YAML frontmatter). */
  skillDirs?: Array<string>
  /** Extra directories to scan for agent files. */
  agentDirs?: Array<string>
  /** Optional queue configuration for lane-based tool execution. */
  queueConfig?: SessionQueueConfig
  /** Allow all tools without HITL confirmation (default: false). */
  permissive?: boolean
  /** Enable planning mode (default: false). */
  planning?: boolean
  /** Enable goal tracking (default: false). */
  goalTracking?: boolean
  /** Max consecutive parse errors before abort. */
  maxParseRetries?: number
  /** Per-tool execution timeout in milliseconds. */
  toolTimeoutMs?: number
  /** Max LLM API failures before abort. */
  circuitBreakerThreshold?: number
  /** Enable auto-compaction when context window fills up (default: false). */
  autoCompact?: boolean
  /** Context usage threshold (0.0–1.0) to trigger auto-compaction (default: 0.8). */
  autoCompactThreshold?: number
  /**
   * Long-term memory store backend.
   *
   * Pass `new FileMemoryStore("./memory")` for file-based persistence.
   * ```js
   * agent.session('.', { memoryStore: new FileMemoryStore('./memory') });
   * ```
   */
  memoryStore?: JsMemoryStore
  /**
   * Session persistence store backend.
   *
   * Pass `new FileSessionStore("./sessions")` to persist sessions to disk,
   * or `new MemorySessionStore()` for an ephemeral in-process store.
   * ```js
   * agent.session('.', {
   *   sessionStore: new FileSessionStore('./sessions'),
   *   sessionId: 'my-session',
   *   autoSave: true,
   * });
   * ```
   */
  sessionStore?: JsSessionStore
  /**
   * Security provider.
   *
   * Pass `new DefaultSecurityProvider()` to enable input taint tracking and
   * output sanitisation. Omit to disable security (default: no security).
   * ```js
   * agent.session('.', { securityProvider: new DefaultSecurityProvider() });
   * ```
   */
  securityProvider?: JsSecurityProvider
  /**
   * Plugins to mount onto this session.
   *
   * Pass instances such as `new SkillPlugin(...)` to inject custom skills.
   */
  plugins?: Array<JsPlugin>
  /**
   * Custom role/identity prepended before the core agentic prompt.
   * Example: "You are a senior Python developer specializing in FastAPI."
   */
  role?: string
  /**
   * Custom coding guidelines appended after the core prompt.
   * Example: "Always use type hints. Follow PEP 8."
   */
  guidelines?: string
  /** Custom response style (replaces default Response Format section). */
  responseStyle?: string
  /** Freeform extra instructions appended at the end. */
  extra?: string
  /**
   * Inline skills registered programmatically without needing skill files on disk.
   * Each entry defines an instruction or persona skill injected into the system prompt.
   */
  inlineSkills?: Array<InlineSkill>
  /** Override maximum number of tool-call rounds for this session. */
  maxToolRounds?: number
  /**
   * Sampling temperature (0.0–1.0). Overrides the provider default.
   * Only applied when `model` is also set.
   */
  temperature?: number
  /**
   * Extended thinking token budget (e.g. 10_000). Enables chain-of-thought reasoning.
   * Only applied when `model` is also set. Provider must support extended thinking.
   */
  thinkingBudget?: number
  /**
   * Enable continuation injection (default: true).
   * When enabled, the loop injects a follow-up prompt when the LLM stops without completing.
   */
  continuationEnabled?: boolean
  /** Maximum continuation injections per execution (default: 3). */
  maxContinuationTurns?: number
  /**
   * Session ID (auto-generated if not set).
   *
   * Set a stable ID so the session can be saved and resumed later:
   * ```js
   * agent.session('.', { sessionId: 'my-session', sessionStore: new FileSessionStore('./sessions'), autoSave: true });
   * // Later:
   * agent.resumeSession('my-session', { sessionStore: new FileSessionStore('./sessions') });
   * ```
   */
  sessionId?: string
  /** Automatically save the session to the configured store after each turn (default: false). */
  autoSave?: boolean
  /**
   * AHP transport configuration for external agent supervision.
   *
   * Pass an AHP transport instance to enable Agent Harness Protocol supervision.
   * All agent lifecycle events will be forwarded to the harness server.
   *
   * ```js
   * // Stdio transport (local child process)
   * agent.session('.', { ahpTransport: new StdioTransport('python', ['ahp_server.py']) });
   *
   * // HTTP transport (remote server)
   * agent.session('.', { ahpTransport: new HttpTransport('http://localhost:8080/ahp') });
   *
   * // WebSocket transport (bidirectional streaming)
   * agent.session('.', { ahpTransport: new WebSocketTransport('ws://localhost:8080/ahp') });
   *
   * // Unix socket transport (local IPC)
   * agent.session('.', { ahpTransport: new UnixSocketTransport('/tmp/ahp.sock') });
   * ```
   */
  ahpTransport?: JsAhpTransport
}
/** A single message in conversation history. */
export interface MessageObject {
  role: string
  content: Array<ContentBlockObject>
}
/** A content block within a message. */
export interface ContentBlockObject {
  type: string
  /** Text content (for "text" blocks). */
  text?: string
  /** Tool use ID (for "tool_use" blocks). */
  id?: string
  /** Tool name (for "tool_use" blocks). */
  name?: string
  /** Tool input (for "tool_use" blocks). */
  input?: any
  /** Tool use ID reference (for "tool_result" blocks). */
  toolUseId?: string
  /** Tool result content (for "tool_result" blocks). */
  resultContent?: string
  /** Whether this is an error result (for "tool_result" blocks). */
  isError?: boolean
}
/** An image attachment for multi-modal prompts. */
export interface AttachmentObject {
  /** Raw image bytes. */
  data: Buffer
  /** MIME type (e.g., "image/jpeg", "image/png"). */
  mediaType: string
}
/** Configuration for the session lane queue. */
export interface SessionQueueConfig {
  /** Max concurrency for Query lane (default: 4). */
  queryConcurrency?: number
  /** Max concurrency for Execute lane (default: 2). */
  executeConcurrency?: number
  /** Max concurrency for Generate lane (default: 1). */
  generateConcurrency?: number
  /** Enable dead letter queue. */
  enableDlq?: boolean
  /** Max DLQ size (default: 1000). */
  dlqMaxSize?: number
  /** Enable metrics collection. */
  enableMetrics?: boolean
  /** Enable queue alerts. */
  enableAlerts?: boolean
  /** Default command timeout (ms). */
  timeoutMs?: number
  /** Enable all features with sensible defaults. */
  enableAllFeatures?: boolean
  /**
   * Per-lane handler config. Keys: "control", "query", "execute", "generate".
   * Values: LaneHandlerConfig with mode ("internal"/"external"/"hybrid") and timeoutMs.
   */
  laneHandlers?: Record<string, LaneHandlerConfig>
}
/** Result of an external task completion. */
export interface ExternalTaskResult {
  success: boolean
  result?: any
  error?: string
}
/** Lane handler configuration. */
export interface LaneHandlerConfig {
  /** "internal", "external", or "hybrid" */
  mode: string
  /** Timeout for external processing (ms). */
  timeoutMs?: number
}
/** Queue statistics. */
export interface QueueStats {
  totalPending: number
  totalActive: number
  externalPending: number
}
export interface McpServerStatusEntry {
  name: string
  connected: boolean
  toolCount: number
  error?: string
}
/** MCP server metadata exposed to slash command handlers. */
export interface CommandMcpServerInfo {
  /** MCP server name. */
  name: string
  /** Number of tools currently exposed by the server. */
  toolCount: number
}
/** Context passed to custom slash command handlers. */
export interface CommandContext {
  /** Current session ID. */
  sessionId: string
  /** Current workspace path. */
  workspace: string
  /** Current active model identifier. */
  model: string
  /** Number of messages in session history. */
  historyLen: number
  /** Total tokens used in this session so far. */
  totalTokens: number
  /** Estimated session cost in USD. */
  totalCost: number
  /** Registered tool names (builtin + MCP). */
  toolNames: Array<string>
  /** Connected MCP servers and their tool counts. */
  mcpServers: Array<CommandMcpServerInfo>
}
/** Metadata about a registered slash command. */
export interface CommandInfo {
  /** Command name without the leading `/` (e.g., `"loop"`, `"help"`) */
  name: string
  /** Short description shown in `/help` */
  description: string
  /** Optional usage hint (e.g., `"/loop [interval] <prompt> [every <interval>]"`) */
  usage?: string
}
/** Info about an active scheduled task. */
export interface ScheduledTaskInfo {
  /** 8-char hex task ID */
  id: string
  /** The prompt sent at each interval */
  prompt: string
  /** Interval between fires in seconds */
  intervalSecs: number
  /** Whether the task repeats (always `true` for tasks created via `/loop`) */
  recurring: boolean
  /** Number of times this task has fired so far */
  fireCount: number
  /** Seconds until the next fire (0 if overdue) */
  nextFireInSecs: number
}
/** Matcher for filtering which events trigger a hook. */
export interface HookMatcherObject {
  /** Match specific tool name (exact match) */
  tool?: string
  /** Match file path pattern (glob) */
  pathPattern?: string
  /** Match command pattern (regex for Bash commands) */
  commandPattern?: string
  /** Match session ID (exact match) */
  sessionId?: string
  /** Match skill name (supports glob patterns) */
  skill?: string
}
/** Configuration for a hook. */
export interface HookConfigObject {
  /** Priority (lower values = higher priority, default: 100) */
  priority?: number
  /** Timeout in milliseconds (default: 30000) */
  timeoutMs?: number
  /** Whether to execute asynchronously (fire-and-forget) */
  asyncExecution?: boolean
  /** Maximum retry attempts */
  maxRetries?: number
}
/** Metadata about a built-in skill. */
export interface SkillInfo {
  name: string
  description: string
  /** Skill kind: "instruction", "tool", or "agent". */
  kind: string
}
/**
 * Return a list of built-in skills compiled into the library.
 *
 * Each entry has `name`, `description`, and `kind` (instruction, tool, or agent).
 */
export declare function builtinSkills(): Array<SkillInfo>
/** Role of a team member. */
export const enum TeamRole {
  /** Decomposes goals into tasks, assigns work. */
  Lead = 0,
  /** Executes assigned tasks. */
  Worker = 1,
  /** Reviews completed work, provides feedback. */
  Reviewer = 2
}
/** Task status on the team task board. */
export const enum TeamTaskStatus {
  /** Waiting to be claimed. */
  Open = 0,
  /** Claimed by a worker. */
  InProgress = 1,
  /** Work done, awaiting review. */
  InReview = 2,
  /** Approved by reviewer. */
  Done = 3,
  /** Rejected, needs rework. */
  Rejected = 4
}
/** Team configuration. */
export interface TeamConfig {
  /** Maximum concurrent tasks on the board (default: 50). */
  maxTasks?: number
  /** Message channel buffer size (default: 128). */
  channelBuffer?: number
  /** Maximum coordinator rounds before `runUntilDone` exits (default: 10). */
  maxRounds?: number
  /** Worker/Reviewer polling interval in milliseconds (default: 200). */
  pollIntervalMs?: number
}
/** A task snapshot from the team board (read-only). */
export interface TeamTask {
  id: string
  description: string
  postedBy: string
  assignedTo?: string
  /** Task status. */
  status: string
  result?: string
  createdAt: number
  updatedAt: number
}
/** Result returned by `TeamRunner.runUntilDone()`. */
export interface TeamRunResult {
  doneTasks: Array<TeamTask>
  rejectedTasks: Array<TeamTask>
  rounds: number
}
/**
 * Per-member overrides for `TeamRunner.addLead`, `addWorker`, and `addReviewer`.
 *
 * All fields are optional. Unset fields inherit from the agent definition
 * file (role-level config) and ultimately from the `Agent` base config:
 *
 * ```
 * TeamMemberOptions  →  AgentDefinition (.yaml/.md)  →  Agent (config.hcl)
 * ```
 *
 * Specifically:
 * - `model`: unset → inherits agent definition model → inherits Agent default model
 * - `extra`: unset → inherits agent definition `prompt` field
 * - `role`, `guidelines`, `responseStyle`: unset → empty (no definition-level equivalent)
 * - `workspace`: unset → inherits the workspace passed to `TeamRunner.create`
 * - `maxToolRounds`: unset → inherits agent definition `max_steps` → inherits Agent config
 */
export interface TeamMemberOptions {
  /**
   * Override the workspace for this member.
   *
   * Set this to an isolated git worktree path so concurrent workers do not
   * conflict with each other on the filesystem.
   * Falls back to the workspace supplied to `TeamRunner.create`.
   */
  workspace?: string
  /**
   * Model override. Format: `"provider/model"` (e.g. `"openai/gpt-4o"`).
   * Falls back to the agent definition model, then the Agent default model.
   */
  model?: string
  /**
   * Custom role/identity prepended before the core agentic prompt.
   *
   * Example: `"You are a senior Python developer specializing in FastAPI."`
   * No definition-level default — omit to use the standard agent identity.
   */
  role?: string
  /**
   * Custom coding guidelines appended after the core prompt.
   *
   * Example: `"Always write unit tests. Follow PEP 8."`
   * No definition-level default — omit to use no extra guidelines.
   */
  guidelines?: string
  /**
   * Custom response style (replaces the default Response Format section).
   * No definition-level default — omit to use the standard response format.
   */
  responseStyle?: string
  /**
   * Freeform extra instructions appended at the very end of the system prompt.
   * Falls back to the agent definition `prompt` field when unset.
   */
  extra?: string
  /**
   * Override maximum number of tool-call rounds for this member's session.
   * Falls back to the agent definition `max_steps`, then the Agent config.
   */
  maxToolRounds?: number
}
/** Configuration for a search engine. */
export interface SearchEngineConfig {
  enabled: boolean
  weight: number
  timeout?: number
}
/** Browser backend for headless search. */
export const enum BrowserBackend {
  /** Chrome/Chromium headless. */
  Chrome = 0,
  /** Lightpanda headless browser (Linux/macOS only). */
  Lightpanda = 1
}
/** Headless browser configuration. */
export interface HeadlessConfig {
  backend: BrowserBackend
  browserPath?: string
  maxTabs?: number
  launchArgs?: Array<string>
}
/** Health monitor configuration for search engines. */
export interface SearchHealthConfig {
  maxFailures: number
  suspendSeconds: number
}
/** Search engine configuration (a3s-search integration). */
export interface SearchConfig {
  timeout: number
  health?: SearchHealthConfig
  engines: Record<string, SearchEngineConfig>
  headless?: HeadlessConfig
}
/** SubAgent configuration for orchestrator. */
export interface SubAgentConfig {
  /** Agent type (general, explore, plan, etc.) */
  agentType: string
  /** Task description */
  description: string
  /** Execution prompt */
  prompt: string
  /** Enable permissive mode (bypass HITL) */
  permissive: boolean
  /** Deny rules to enforce even in permissive mode (e.g., ["mcp__longvt__*"]) */
  permissiveDeny?: Array<string>
  /** Maximum execution steps */
  maxSteps?: number
  /** Execution timeout (milliseconds) */
  timeoutMs?: number
  /** Parent SubAgent ID (for nesting) */
  parentId?: string
  /** Workspace directory for the SubAgent (defaults to ".") */
  workspace?: string
  /** Extra directories to scan for agent definition files */
  agentDirs?: Array<string>
  /** Extra directories to scan for skill definition files */
  skillDirs?: Array<string>
  /**
   * Lane queue config for External/Hybrid tool dispatch.
   * When set, tools in the specified lanes are routed to external workers.
   */
  laneConfig?: SessionQueueConfig
}
/**
 * Unified agent slot — used for both standalone subagents and team members.
 *
 * When `role` is `undefined` the slot describes a standalone subagent.
 * Valid role values: `"lead"`, `"worker"`, `"reviewer"`.
 */
export interface AgentSlot {
  /** Agent type (general, explore, plan, etc.) */
  agentType: string
  /** Team role: "lead", "worker", or "reviewer". Omit for standalone. */
  role?: string
  /** Task description */
  description: string
  /** Execution prompt */
  prompt: string
  /** Enable permissive mode (bypass HITL) */
  permissive: boolean
  /** Deny rules to enforce even in permissive mode (e.g., ["mcp__longvt__*"]) */
  permissiveDeny?: Array<string>
  /** Maximum execution steps */
  maxSteps?: number
  /** Execution timeout (milliseconds) */
  timeoutMs?: number
  /** Parent SubAgent ID (for nesting) */
  parentId?: string
  /** Workspace directory (defaults to ".") */
  workspace?: string
  /** Extra directories to scan for agent definition files */
  agentDirs?: Array<string>
  /** Extra directories to scan for skill definition files */
  skillDirs?: Array<string>
  /** Lane queue config for External/Hybrid tool dispatch */
  laneConfig?: SessionQueueConfig
}
/** SubAgent activity type */
export interface SubAgentActivity {
  /** Activity type: idle, calling_tool, requesting_llm, waiting_for_control */
  activityType: string
  /** Activity data (JSON string) */
  data?: string
}
/** SubAgent information with metadata and current activity */
export interface SubAgentInfo {
  id: string
  agentType: string
  description: string
  state: string
  parentId?: string
  createdAt: number
  updatedAt: number
  currentActivity?: SubAgentActivity
}
/** SubAgent activity entry (id + activity) */
export interface SubAgentActivityEntry {
  id: string
  activity: SubAgentActivity
}
/** SubAgent state entry (id + state) */
export interface SubAgentStateEntry {
  id: string
  state: string
}
/** A pending external task waiting for a remote worker to process. */
export interface PendingExternalTask {
  /** Unique task identifier — pass this to `completeExternalTask()` */
  taskId: string
  /** Tool type: "bash", "write", "edit", etc. */
  commandType: string
  /** JSON-encoded tool arguments */
  payload: string
  /** Lane name: "Execute", "Query", etc. */
  lane: string
}
/** Streaming event iterator. Use `for await (const event of stream)` or call `.next()` manually. */
export declare class EventStream {
  /**
   * Get the next event from the stream.
   *
   * Returns `{ value: AgentEvent | null, done: boolean }`.
   * When `done` is true, the stream is exhausted.
   */
  next(): Promise<NextResult>
}
/**
 * File-backed long-term memory store.
 *
 * ```js
 * agent.session('.', { memoryStore: new FileMemoryStore('./memory') });
 * ```
 */
export declare class FileMemoryStore {
  backend: string
  dir: string
  /** Create a file-backed memory store at `dir`. */
  constructor(dir: string)
}
/**
 * File-backed session store (persists sessions to disk for later resumption).
 *
 * ```js
 * agent.session('.', {
 *   sessionStore: new FileSessionStore('./sessions'),
 *   sessionId: 'my-session',
 *   autoSave: true,
 * });
 * ```
 */
export declare class FileSessionStore {
  backend: string
  dir: string
  /** Create a file-backed session store at `dir`. */
  constructor(dir: string)
}
/**
 * In-memory (non-persistent) session store.
 *
 * Useful for testing, ephemeral runs, and CI pipelines where no disk state is needed.
 *
 * ```js
 * agent.session('.', { sessionStore: new MemorySessionStore() });
 * ```
 */
export declare class MemorySessionStore {
  backend: string
  constructor()
}
/**
 * Default security provider: input taint tracking + output sanitisation.
 *
 * ```js
 * agent.session('.', { securityProvider: new DefaultSecurityProvider() });
 * ```
 */
export declare class DefaultSecurityProvider {
  kind: string
  constructor()
}
/**
 * Skill-only plugin — injects custom skills into the session's skill registry
 * without registering any tools.
 *
 * Use this to add custom LLM guidance (instructions, tool restrictions,
 * prompting strategies) directly from Node.js. For tools, use MCP servers.
 *
 * ```js
 * import { SkillPlugin } from '@a3s-lab/code';
 *
 * const plugin = new SkillPlugin('my-plugin', [`
 * ---
 * name: my-skill
 * description: Use bash cautiously
 * allowed-tools: "bash(*)"
 * kind: instruction
 * ---
 * Always explain what command you're about to run before executing it.
 * `]);
 *
 * agent.session('.', { plugins: [plugin] });
 * ```
 */
export declare class SkillPlugin {
  kind: string
  pluginName?: string
  skills?: Array<string>
  constructor(name: string, skills: Array<string>)
}
/**
 * Stdio transport for AHP (Agent Harness Protocol).
 *
 * Launches a child process and communicates via stdin/stdout using JSON-RPC 2.0.
 *
 * ```js
 * agent.session('.', {
 *   ahpTransport: new StdioTransport('python', ['ahp_server.py'])
 * });
 * ```
 */
export declare class StdioTransport {
  kind: string
  program?: string
  args?: Array<string>
  url?: string
  authToken?: string
  path?: string
  constructor(program: string, args: Array<string>)
}
/**
 * HTTP transport for AHP (Agent Harness Protocol).
 *
 * Connects to a remote AHP harness server via HTTP.
 *
 * ```js
 * agent.session('.', {
 *   ahpTransport: new HttpTransport('http://localhost:8080/ahp')
 * });
 * ```
 */
export declare class HttpTransport {
  kind: string
  program?: string
  args?: Array<string>
  url?: string
  authToken?: string
  path?: string
  constructor(url: string, authToken?: string | undefined | null)
}
/**
 * WebSocket transport for AHP (Agent Harness Protocol).
 *
 * Connects to a remote AHP harness server via WebSocket for bidirectional streaming.
 *
 * ```js
 * agent.session('.', {
 *   ahpTransport: new WebSocketTransport('ws://localhost:8080/ahp')
 * });
 * ```
 */
export declare class WebSocketTransport {
  kind: string
  program?: string
  args?: Array<string>
  url?: string
  authToken?: string
  path?: string
  constructor(url: string, authToken?: string | undefined | null)
}
/**
 * Unix socket transport for AHP (Agent Harness Protocol).
 *
 * Connects to a local AHP harness server via Unix domain socket.
 *
 * ```js
 * agent.session('.', {
 *   ahpTransport: new UnixSocketTransport('/tmp/ahp.sock')
 * });
 * ```
 */
export declare class UnixSocketTransport {
  kind: string
  program?: string
  args?: Array<string>
  url?: string
  authToken?: string
  path?: string
  constructor(path: string)
}
/** AI coding agent. Create with `Agent.create()`, then call `agent.session()`. */
export declare class Agent {
  /**
   * Create an Agent from a config file path or inline config string.
   *
   * Accepts HCL (.hcl), JSON (.json), ACL (.acl), or inline config strings.
   * For inline strings: JSON starts with '{', ACL starts with 'providers "', otherwise HCL.
   *
   * @param configSource - Path to a config file (.hcl/.json/.acl), or inline config string
   */
  static create(configSource: string): Promise<Agent>
  /**
   * Re-fetch tool definitions from all connected global MCP servers and
   * update the agent-level cache.
   *
   * New sessions created after this call will see the refreshed tool list.
   * Existing sessions are unaffected.
   */
  refreshMcpTools(): Promise<void>
  /**
   * Bind to a workspace directory, returning a Session.
   *
   * @param workspace - Path to the workspace directory
   * @param options - Optional session overrides
   */
  session(workspace: string, options?: SessionOptions | undefined | null): Session
  /**
   * Resume a previously saved session by ID.
   *
   * `options.sessionStore` must be set to a `FileSessionStore` (or `MemorySessionStore`)
   * that points to the directory where the session was originally saved.
   *
   * ```js
   * const session = agent.resumeSession('my-session', {
   *   sessionStore: new FileSessionStore('./sessions'),
   * });
   * ```
   *
   * @param sessionId - The session ID to resume
   * @param options - Session options; `sessionStore` is required
   */
  resumeSession(sessionId: string, options: SessionOptions): Session
  /**
   * Create a session pre-configured from a named agent definition.
   *
   * Loads the agent by name from built-in agents and optionally from
   * additional directories, then creates a session with the agent's
   * permissions, system prompt, model, and step limit applied.
   *
   * @param workspace - Path to the workspace directory
   * @param agentName - Name of the agent to load (e.g. "explore", "general")
   * @param agentDirs - Optional directories to scan for agent files
   * @param options - Optional session overrides layered on top of the agent definition
   */
  sessionForAgent(workspace: string, agentName: string, agentDirs?: Array<string> | undefined | null, options?: SessionOptions | undefined | null): Session
}
/** Workspace-bound session. All LLM and tool operations happen here. */
export declare class Session {
  /**
   * Send a prompt and wait for the complete response.
   *
   * @param prompt - The prompt to send
   * @param history - Optional conversation history
   */
  send(prompt: string, history?: Array<MessageObject> | undefined | null): Promise<AgentResult>
  /**
   * Ask an ephemeral side question without affecting conversation history.
   *
   * Takes a read-only snapshot of the current history, makes a separate LLM
   * call with no tools, and returns the answer. History is never modified.
   *
   * Safe to call concurrently with an ongoing `send()` — the snapshot only
   * acquires a read lock on the internal history.
   *
   * @param question - The side question to ask
   * @returns BtwResult with question, answer, and token usage
   */
  btw(question: string): Promise<BtwResult>
  /**
   * Send a prompt and get a streaming event iterator.
   *
   * Returns an `EventStream`. Use `for await (const event of stream)` or call `.next()` manually.
   *
   * @param prompt - The prompt to send
   * @param history - Optional conversation history
   */
  stream(prompt: string, history?: Array<MessageObject> | undefined | null): Promise<EventStream>
  /**
   * Send a prompt with image attachments and wait for the complete response.
   *
   * @param prompt - The prompt to send
   * @param attachments - Array of `{ data: Buffer, mediaType: string }`
   * @param history - Optional conversation history
   */
  sendWithAttachments(prompt: string, attachments: Array<AttachmentObject>, history?: Array<MessageObject> | undefined | null): Promise<AgentResult>
  /**
   * Stream a prompt with image attachments.
   *
   * @param prompt - The prompt to send
   * @param attachments - Array of `{ data: Buffer, mediaType: string }`
   * @param history - Optional conversation history
   */
  streamWithAttachments(prompt: string, attachments: Array<AttachmentObject>, history?: Array<MessageObject> | undefined | null): Promise<EventStream>
  /** Return the session's conversation history. */
  history(): Array<MessageObject>
  /** Execute a tool by name, bypassing the LLM. */
  tool(name: string, args: any): Promise<ToolResult>
  /**
   * Run a goal through the built-in `run_team` tool.
   *
   * Spawns a Lead → Worker → Reviewer team as child subagents: the Lead
   * decomposes `goal` into tasks, Workers execute them concurrently, and the
   * Reviewer approves or rejects each result (rejected tasks are retried).
   *
   * This is a typed convenience wrapper over `session.tool("run_team", {...})`.
   * All agent-type arguments default to `"general"` when omitted.
   *
   * @returns `ToolResult` whose `output` contains the formatted team run summary.
   */
  runTeam(goal: string, leadAgent?: string | undefined | null, workerAgent?: string | undefined | null, reviewerAgent?: string | undefined | null, maxSteps?: number | undefined | null): Promise<ToolResult>
  /** Read a file from the workspace. */
  readFile(path: string): Promise<string>
  /** Execute a bash command in the workspace. */
  bash(command: string): Promise<string>
  /** Search for files matching a glob pattern. */
  glob(pattern: string): Promise<Array<string>>
  /** Search file contents with a regex pattern. */
  grep(pattern: string): Promise<string>
  /** Search the web using multiple search engines. */
  webSearch(params: JsWebSearchParams): Promise<ToolResult>
  /** Execute a git command (status, log, branch, checkout, diff, stash, remote, worktree). */
  git(command: string, subcommand?: string | undefined | null, name?: string | undefined | null, path?: string | undefined | null, newBranch?: boolean | undefined | null, base?: string | undefined | null, force?: boolean | undefined | null, maxCount?: number | undefined | null, message?: string | undefined | null, includeUntracked?: boolean | undefined | null, target?: string | undefined | null, reference?: string | undefined | null): Promise<ToolResult>
  /** Check if this session has a lane queue configured. */
  hasQueue(): boolean
  /**
   * Configure a lane's handler mode.
   *
   * @param lane - "control", "query", "execute", or "generate"
   * @param config - { mode: "internal"|"external"|"hybrid", timeoutMs?: number }
   */
  setLaneHandler(lane: string, config: LaneHandlerConfig): Promise<void>
  /**
   * Complete an external task by ID.
   *
   * @param taskId - The task identifier
   * @param result - { success: boolean, result?: any, error?: string }
   * @returns true if found, false if not found
   */
  completeExternalTask(taskId: string, result: ExternalTaskResult): Promise<boolean>
  /** Get pending external tasks. */
  pendingExternalTasks(): Promise<any>
  /** Get queue statistics. */
  queueStats(): Promise<QueueStats>
  /**
   * Submit a JSON payload as a command to the session's lane queue.
   *
   * The payload is stored and returned as-is when the queue schedules the
   * command. Returns a Promise that resolves to the payload value.
   *
   * @param lane - "control", "query", "execute", or "generate"
   * @param payload - Any JSON-serializable value
   */
  submit(lane: string, payload: any): Promise<any>
  /**
   * Submit multiple JSON payloads as a batch to the session's lane queue.
   *
   * More efficient than calling `submit()` in a loop. Returns a Promise that
   * resolves to an array of results in the same order as the input payloads.
   *
   * @param lane - "control", "query", "execute", or "generate"
   * @param payloads - Array of JSON-serializable values
   */
  submitBatch(lane: string, payloads: Array<any>): Promise<Array<any>>
  /** Get dead letters from the DLQ. */
  deadLetters(): Promise<any>
  /**
   * Get a detailed metrics snapshot from the queue.
   *
   * Returns `null` if metrics are not enabled (queue not configured or
   * `enable_metrics` was not set in `SessionQueueConfig`).
   *
   * @returns Object with `counters`, `gauges`, and `histograms` maps, or null
   */
  queueMetrics(): Promise<any>
  /**
   * Add an MCP server to this live session.
   *
   * Connects the server and registers all its tools immediately so the agent
   * can call them. Tool names follow the convention `mcp__<name>__<tool>`.
   *
   * @param name - Server identifier (used as prefix in tool names)
   * @param transport - Transport type: `"stdio"` (default), `"http"`, or `"streamable-http"`
   * @param command - Executable to launch (stdio only, e.g. `"npx"`)
   * @param args - Arguments for the command (stdio only)
   * @param url - Server URL (http / streamable-http only)
   * @param headers - HTTP headers (http / streamable-http only)
   * @param env - Optional extra environment variables (stdio only)
   * @returns Number of tools registered from the server
   */
  addMcpServer(name: string, transport?: 'stdio' | 'http' | 'streamable-http', command?: string | undefined | null, args?: Array<string> | undefined | null, url?: string | undefined | null, headers?: Record<string, string> | undefined | null, env?: Record<string, string> | undefined | null, timeoutMs?: number | undefined | null): Promise<number>
  /**
   * Dynamically register agent definitions from a directory into the live session.
   *
   * Scans the directory for `*.yaml`, `*.yml`, and `*.md` agent definition files
   * and registers them into the shared AgentRegistry used by the `task` tool.
   * New agents are immediately callable via `task({ agent: "…", … })` without
   * restarting the session.
   *
   * @param path - Directory to scan for agent definition files
   * @returns Number of agents successfully loaded
   */
  registerAgentDir(path: string): number
  /**
   * Disconnect and unregister an MCP server, removing its tools from the session.
   *
   * @param name - Server name (must match the name used in addMcpServer)
   */
  removeMcpServer(name: string): Promise<void>
  /**
   * Return connection status for all MCP servers registered on this session.
   *
   * @returns Array of `{ name, connected, toolCount }` entries
   */
  mcpStatus(): Promise<Array<McpServerStatusEntry>>
  /**
   * Return the names of all tools currently registered on this session.
   *
   * @returns Array of tool name strings
   */
  toolNames(): Array<string>
  /**
   * Register a hook for lifecycle event interception.
   *
   * Hooks registered on a session are automatically propagated to all sub-agents
   * spawned by the `task` tool, including grandchild agents at arbitrary depth.
   * This ensures security hooks (e.g. a sentinel) apply across the full agent tree
   * without requiring explicit registration on each sub-agent session.
   *
   * @param hookId - Unique hook identifier
   * @param eventType - Event type: "pre_tool_use", "post_tool_use", "generate_start",
   *   "generate_end", "session_start", "session_end", "skill_load", "skill_unload",
   *   "pre_prompt", "post_response", "on_error"
   * @param matcher - Optional matcher: { tool?, pathPattern?, commandPattern?, sessionId?, skill? }
   * @param config - Optional config: { priority?, timeoutMs?, asyncExecution?, maxRetries? }
   * @param handler - Optional callback `(event: any) => { action: 'continue' | 'block' | 'skip',
   *   reason?: string } | null`. When provided, the function is called for every matching event
   *   and its return value controls execution. Return `{ action: 'block', reason: '...' }` to
   *   cancel the operation, `{ action: 'skip' }` to skip remaining hooks, or `null`/`undefined`
   *   for continue. Hooks with no handler still fire (observable via stream events) but always
   *   continue.
   */
  registerHook(hookId: string, eventType: string, matcher?: HookMatcherObject | undefined | null, config?: HookConfigObject | undefined | null, handler?: ((event: Record<string, unknown>) => { action: string; reason?: string } | null | undefined) | null | undefined): void
  /**
   * Unregister a hook by ID.
   *
   * @param hookId - The hook identifier to remove
   * @returns true if the hook was found and removed
   */
  unregisterHook(hookId: string): boolean
  /** Get the number of registered hooks. */
  hookCount(): number
  /** Return the session ID. */
  get sessionId(): string
  /** Return the workspace path. */
  get workspace(): string
  /** Return any deferred init warning (e.g. memory store failed to initialize). */
  get initWarning(): string | null
  /** Save the session to the configured store. */
  save(): Promise<void>
  /** Check if memory is configured for this session. */
  get hasMemory(): boolean
  /**
   * Remember a successful task execution.
   *
   * @param task - Description of the task
   * @param tools - List of tool names used
   * @param result - Summary of the result
   */
  rememberSuccess(task: string, tools: Array<string>, result: string): Promise<void>
  /**
   * Remember a failed task execution.
   *
   * @param task - Description of the task
   * @param error - Error message
   * @param tools - List of tool names attempted
   */
  rememberFailure(task: string, error: string, tools: Array<string>): Promise<void>
  /**
   * Recall memories similar to a query.
   *
   * @param query - Search query
   * @param limit - Maximum number of results (default: 5)
   * @returns Array of memory items
   */
  recallSimilar(query: string, limit?: number | undefined | null): Promise<any>
  /**
   * Recall memories by tags.
   *
   * @param tags - Tags to search for
   * @param limit - Maximum number of results (default: 10)
   * @returns Array of memory items
   */
  recallByTags(tags: Array<string>, limit?: number | undefined | null): Promise<any>
  /**
   * Get recent memory items.
   *
   * @param limit - Maximum number of results (default: 10)
   * @returns Array of memory items
   */
  memoryRecent(limit?: number | undefined | null): Promise<any>
  /**
   * Get memory statistics.
   *
   * @returns Object with longTermCount, shortTermCount, workingCount
   */
  memoryStats(): Promise<any>
  /**
   * Get current working memory items.
   *
   * Working memory holds the active context items for the current task.
   *
   * @returns Array of memory items currently in working memory
   */
  getWorking(): Promise<any>
  /**
   * Clear working memory.
   *
   * Removes all items from working memory without affecting short-term or long-term memory.
   */
  clearWorking(): Promise<void>
  /**
   * Get current short-term memory items.
   *
   * Short-term memory contains items stored during this session.
   *
   * @returns Array of memory items in short-term memory
   */
  getShortTerm(): Promise<any>
  /**
   * Clear short-term memory for this session.
   *
   * Removes all session-scoped memory items without affecting long-term or working memory.
   */
  clearShortTerm(): Promise<void>
  /**
   * Register a custom slash command.
   *
   * Slash commands are invoked via `session.send("/command args")` and execute
   * before the LLM sees the input. The handler receives the command arguments
   * and a context object with session metadata.
   *
   * @param name - Command name without the leading `/` (e.g., `"status"`)
   * @param description - Short description shown in `/help`
   * @param handler - Callback `(args: string, ctx: CommandContext) => string`
   *
   * @example
   * ```typescript
   * session.registerCommand("status", "Show session info", (args, ctx) => {
   *   return `Session ${ctx.sessionId} in ${ctx.workspace}`;
   * });
   * await session.send("/status");
   * ```
   */
  registerCommand(name: string, description: string, handler: (args: string, ctx: CommandContext) => string): void
  /**
   * List all registered slash commands.
   *
   * Returns each command's name, description, and optional usage hint.
   * Slash commands can be invoked via `session.send("/command args")`.
   *
   * @returns Array of CommandInfo objects sorted by name
   */
  listCommands(): Array<CommandInfo>
  /**
   * Schedule a recurring prompt to fire at a given interval.
   *
   * This is the programmatic equivalent of `/loop <interval>s <prompt>`.
   * The scheduled prompt runs automatically after each `send()` call when it is due.
   *
   * @param prompt - The prompt to send at each interval
   * @param intervalSecs - Interval in seconds (minimum: 1)
   * @returns 8-char hex task ID (use with `cancelScheduledTask`)
   */
  scheduleTask(prompt: string, intervalSecs: number): string
  /**
   * List all active scheduled tasks for this session.
   *
   * @returns Array of ScheduledTaskInfo objects sorted by task ID
   */
  listScheduledTasks(): Array<ScheduledTaskInfo>
  /**
   * Cancel a scheduled task by ID.
   *
   * @param id - Task ID returned by `scheduleTask` or listed by `listScheduledTasks`
   * @returns `true` if the task was found and cancelled
   */
  cancelScheduledTask(id: string): boolean
  /**
   * Cancel the current ongoing operation (send/stream).
   *
   * If an operation is in progress, this will trigger cancellation of the LLM streaming
   * and tool execution. The operation will terminate as soon as possible.
   *
   * @returns `true` if an operation was cancelled, `false` if no operation was in progress
   */
  cancel(): boolean
  /**
   * Close the session and stop background tasks such as the cron ticker.
   *
   * Call this when the session will no longer be used so Node.js can exit
   * cleanly without waiting on session-scoped background workers.
   */
  close(): void
}
/**
 * Shared task board for team coordination.
 *
 * Use `Team.taskBoard()` or `TeamRunner.taskBoard()` to access the board.
 */
export declare class TeamTaskBoard {
  /**
   * Post a new task. Returns the task ID, or null if the board is full.
   *
   * @param description - Task description
   * @param postedBy - Member ID posting the task
   * @param assignTo - Optional member ID to pre-assign the task to
   */
  post(description: string, postedBy: string, assignTo?: string | undefined | null): string | null
  /** Claim the next open or rejected task for a member. */
  claim(memberId: string): TeamTask | null
  /** Mark a task as complete with a result. Returns true if found. */
  complete(taskId: string, result: string): boolean
  /** Approve a task (reviewer action). Returns true if the task was in InReview state. */
  approve(taskId: string): boolean
  /** Reject a task back to open (reviewer action). Returns true if found. */
  reject(taskId: string): boolean
  /** Get a task by ID. */
  get(taskId: string): TeamTask | null
  /** Get all tasks with the given status. */
  byStatus(status: TeamTaskStatus): Array<TeamTask>
  /** Get all tasks assigned to a member. */
  byAssignee(memberId: string): Array<TeamTask>
  /** Summary stats as `{ open, inProgress, inReview, done, rejected }`. */
  stats(): any
  /** Total number of tasks on the board. */
  get len(): number
  /** True if the board has no tasks. */
  get isEmpty(): boolean
}
/**
 * Multi-agent team coordinator.
 *
 * Create the team, add members, then pass it to `TeamRunner` to execute.
 *
 * @example
 * ```js
 * const team = new Team("refactor-auth");
 * team.addMember("lead", TeamRole.Lead);
 * team.addMember("worker-1", TeamRole.Worker);
 * team.addMember("reviewer", TeamRole.Reviewer);
 * const runner = new TeamRunner(team);
 * runner.bindSession("lead", leadSession);
 * const result = await runner.runUntilDone("Refactor the auth module");
 * ```
 */
export declare class Team {
  /**
   * Create a new team.
   *
   * @param name - Team name
   * @param config - Optional `TeamConfig` (uses defaults if omitted)
   */
  constructor(name: string, config?: TeamConfig | undefined | null)
  /**
   * Add a member to the team.
   *
   * @param memberId - Unique member identifier
   * @param role - TeamRole: Lead, Worker, or Reviewer
   */
  addMember(memberId: string, role: TeamRole): void
  /** Remove a member. Returns true if the member was found. */
  removeMember(memberId: string): boolean
  /** Number of registered members. */
  get memberCount(): number
  /** Get the shared task board for inspection. */
  taskBoard(): TeamTaskBoard
}
/**
 * Binds an agent team to real `Session` executors and runs the workflow.
 *
 * The team object is consumed on construction.
 *
 * @example
 * ```js
 * const runner = new TeamRunner(team);
 * runner.bindSession("lead", leadSession);
 * runner.bindSession("worker-1", workerSession);
 * runner.bindSession("reviewer", reviewerSession);
 * const result = await runner.runUntilDone("Build the feature");
 * for (const task of result.doneTasks) {
 *   console.log(task.id, task.result);
 * }
 * ```
 */
export declare class TeamRunner {
  /**
   * Create a runner from a team.
   *
   * The team is consumed: further calls on the original `Team` object will throw.
   */
  constructor(team: Team)
  /**
   * Create a runner with a default agent context.
   *
   * Stores the agent, workspace, and agent directories once so that
   * subsequent calls to `addLead`, `addWorker`, and `addReviewer` do not
   * need to repeat them.
   *
   * @param agent - The `Agent` to create sessions from
   * @param workspace - Path to the workspace directory shared by all members
   * @param agentDirs - Directories to scan for agent definition files
   */
  static create(agent: Agent, workspace: string, agentDirs?: Array<string> | undefined | null): TeamRunner
  /**
   * Add a Lead member bound to the named agent definition.
   *
   * Requires the runner to have been created with `TeamRunner.create(...)`.
   * The member ID is fixed to `"lead"`.
   *
   * Unset fields in `opts` inherit from the agent definition, then from the
   * `Agent` base config (see `TeamMemberOptions` for the full inheritance chain).
   *
   * @param agentName - Name of the agent definition (e.g. `"orchestrator"`)
   * @param opts - Optional per-member overrides; omit to use agent definition defaults
   */
  addLead(agentName: string, opts?: TeamMemberOptions | undefined | null): void
  /**
   * Add a Worker member bound to the named agent definition.
   *
   * Requires the runner to have been created with `TeamRunner.create(...)`.
   * Member IDs are auto-generated as `"worker-1"`, `"worker-2"`, etc.
   * Call this multiple times to add concurrent workers.
   *
   * Set `opts.workspace` to a git worktree path to give each worker an
   * isolated filesystem so concurrent writes do not conflict.
   * Unset fields inherit from the agent definition, then from the `Agent`
   * base config (see `TeamMemberOptions` for the full inheritance chain).
   *
   * @param agentName - Name of the agent definition (e.g. `"general"`)
   * @param opts - Optional per-member overrides; omit to use agent definition defaults
   */
  addWorker(agentName: string, opts?: TeamMemberOptions | undefined | null): void
  /**
   * Add a Reviewer member bound to the named agent definition.
   *
   * Requires the runner to have been created with `TeamRunner.create(...)`.
   * The member ID is fixed to `"reviewer"`.
   *
   * Unset fields in `opts` inherit from the agent definition, then from the
   * `Agent` base config (see `TeamMemberOptions` for the full inheritance chain).
   *
   * @param agentName - Name of the agent definition (e.g. `"reviewer"`)
   * @param opts - Optional per-member overrides; omit to use agent definition defaults
   */
  addReviewer(agentName: string, opts?: TeamMemberOptions | undefined | null): void
  /**
   * Bind a `Session` to a team member.
   *
   * @param memberId - The member ID (must match a member added to the team)
   * @param session - A `Session` object from `Agent.session()`
   */
  bindSession(memberId: string, session: Session): void
  /**
   * Bind a team member to a named agent definition.
   *
   * Loads the agent by name from built-in agents and optionally from
   * additional directories, then creates and binds a session with the
   * agent's permissions, system prompt, model, and step limit applied.
   *
   * @param memberId - The member ID (must match a member added to the team)
   * @param agent - The `Agent` to create the session from
   * @param workspace - Path to the workspace directory
   * @param agentName - Name of the agent to load (e.g. "explore", "general")
   * @param agentDirs - Optional directories to scan for agent files
   */
  bindAgent(memberId: string, agent: Agent, workspace: string, agentName: string, agentDirs?: Array<string> | undefined | null): void
  /** Get the shared task board for inspection. */
  taskBoard(): TeamTaskBoard
  /**
   * Run the Lead → Worker → Reviewer workflow until all tasks are done.
   *
   * 1. The Lead member decomposes `goal` into tasks via JSON response.
   * 2. Worker members concurrently claim and execute tasks.
   * 3. The Reviewer member approves or rejects completed tasks.
   * 4. Rejected tasks re-enter the work queue for retry.
   *
   * @param goal - High-level goal to decompose and execute
   * @returns `TeamRunResult` with `doneTasks`, `rejectedTasks`, and `rounds`
   */
  runUntilDone(goal: string): Promise<TeamRunResult>
}
/** SubAgent handle for control and monitoring. */
export declare class SubAgentHandle {
  /** Get SubAgent ID */
  get id(): string
  /** Get current state (non-blocking) */
  state(): string
  /** Get current activity */
  activity(): SubAgentActivity
  /** Pause execution */
  pause(): void
  /** Resume execution */
  resume(): void
  /** Cancel execution */
  cancel(): void
  /** Wait for completion and get result */
  wait(): string
  /** Subscribe to sub-agent events. */
  events(): SubAgentEventStream
}
/** SubAgent event stream for monitoring sub-agent events. */
export declare class SubAgentEventStream {
  /** Receive the next sub-agent event, or `null` on timeout / end-of-stream. */
  recv(timeoutMs?: number | undefined | null): Promise<any | null>
}
/** Agent Orchestrator for main-sub agent coordination. */
export declare class Orchestrator {
  /**
   * Create a new orchestrator.
   *
   * @param agent - Optional `Agent` instance. When provided, spawned SubAgents
   *                execute real LLM calls using the agent's configuration.
   *                When omitted, SubAgents run in placeholder mode.
   */
  static create(agent?: Agent | undefined | null): Orchestrator
  /** Spawn a new SubAgent */
  spawnSubagent(config: SubAgentConfig): SubAgentHandle
  /**
   * Spawn a subagent from a unified `AgentSlot` declaration.
   *
   * Convenience wrapper over `spawnSubagent` that accepts the unified slot
   * type.  The `role` field is ignored for standalone spawning — use
   * `runTeam` for team-based workflows.
   */
  spawn(slot: AgentSlot): SubAgentHandle
  /**
   * Run a goal through a Lead → Worker → Reviewer team built from AgentSlots.
   *
   * Requires `Orchestrator.create(agent)` mode — returns an error if no backing
   * Agent is configured.  Each slot's `role` field determines its position in the
   * team; slots without a role default to Worker.
   *
   * @returns `TeamRunResult` with `doneTasks`, `rejectedTasks`, and `rounds`.
   */
  runTeam(goal: string, workspace: string, slots: Array<AgentSlot>): Promise<TeamRunResult>
  /** Get active SubAgent count */
  activeCount(): number
  /** Get all SubAgent information list */
  listSubagents(): Array<SubAgentInfo>
  /** Get specific SubAgent information */
  getSubagentInfo(id: string): SubAgentInfo | null
  /** Get all active SubAgent activities */
  getActiveActivities(): Array<SubAgentActivityEntry>
  /** Get all SubAgent states */
  getAllStates(): Array<SubAgentStateEntry>
  /** Pause a SubAgent */
  pauseSubagent(id: string): void
  /** Resume a SubAgent */
  resumeSubagent(id: string): void
  /** Cancel a SubAgent */
  cancelSubagent(id: string): void
  /** Wait for all SubAgents to complete */
  waitAll(): void
  /**
   * Return any external tasks currently waiting for the given SubAgent.
   *
   * Returns an empty array when no tasks are pending or the SubAgent is not found.
   */
  pendingExternalTasksFor(subagentId: string): Array<PendingExternalTask>
  /**
   * Complete an external task dispatched to a remote worker.
   *
   * Returns `true` if the task was found and completed, `false` if no
   * session with the given `subagent_id` is currently registered.
   */
  completeExternalTask(subagentId: string, taskId: string, result: ExternalTaskResult): boolean
}
