/* auto-generated by napi-rs — do not edit by hand */

// ============================================================================
// AgentResult
// ============================================================================

export interface AgentResult {
  text: string;
  toolCallsCount: number;
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
}

// ============================================================================
// AgentEvent
// ============================================================================

export interface AgentEvent {
  type: string;
  text?: string;
  toolName?: string;
  toolId?: string;
  toolOutput?: string;
  exitCode?: number;
  turn?: number;
  prompt?: string;
  error?: string;
  totalTokens?: number;
}

// ============================================================================
// ToolResult
// ============================================================================

export interface ToolResult {
  name: string;
  output: string;
  exitCode: number;
}

// ============================================================================
// EventStream
// ============================================================================

export interface NextResult {
  value: AgentEvent | null;
  done: boolean;
}

export declare class EventStream {
  next(): Promise<NextResult>;
}

// ============================================================================
// SessionOptions
// ============================================================================

export interface SessionOptions {
  model?: string;
  builtinSkills?: boolean;
  skillDirs?: string[];
  agentDirs?: string[];
  queueConfig?: SessionQueueConfig;
  permissive?: boolean;
  planning?: boolean;
  goalTracking?: boolean;
  maxParseRetries?: number;
  toolTimeoutMs?: number;
  circuitBreakerThreshold?: number;
  autoCompact?: boolean;
  autoCompactThreshold?: number;
  memoryDir?: string;
  defaultSecurity?: boolean;
  role?: string;
  guidelines?: string;
  responseStyle?: string;
  extra?: string;
}

export interface MessageObject {
  role: string;
  content: ContentBlockObject[];
}

export interface ContentBlockObject {
  type: string;
  text?: string;
  id?: string;
  name?: string;
  input?: unknown;
  toolUseId?: string;
  resultContent?: string;
  isError?: boolean;
}

export interface AttachmentObject {
  data: Buffer;
  mediaType: string;
}

// ============================================================================
// SessionQueueConfig
// ============================================================================

export interface SessionQueueConfig {
  queryConcurrency?: number;
  executeConcurrency?: number;
  generateConcurrency?: number;
  enableDlq?: boolean;
  dlqMaxSize?: number;
  enableMetrics?: boolean;
  enableAlerts?: boolean;
  timeoutMs?: number;
  enableAllFeatures?: boolean;
}

export interface ExternalTaskResult {
  success: boolean;
  result?: unknown;
  error?: string;
}

export interface LaneHandlerConfig {
  /** "internal", "external", or "hybrid" */
  mode: string;
  timeoutMs?: number;
}

export interface QueueStats {
  totalPending: number;
  totalActive: number;
  externalPending: number;
}

// ============================================================================
// Hook Types
// ============================================================================

export interface HookMatcherObject {
  tool?: string;
  pathPattern?: string;
  commandPattern?: string;
  sessionId?: string;
  skill?: string;
}

export interface HookConfigObject {
  priority?: number;
  timeoutMs?: number;
  asyncExecution?: boolean;
  maxRetries?: number;
}

// ============================================================================
// SkillInfo
// ============================================================================

export interface SkillInfo {
  name: string;
  description: string;
  /** "instruction", "tool", or "agent" */
  kind: string;
}

// ============================================================================
// Search Types
// ============================================================================

export interface SearchEngineConfig {
  enabled: boolean;
  weight: number;
  timeout?: number;
}

export interface SearchHealthConfig {
  maxFailures: number;
  suspendSeconds: number;
}

export interface SearchConfig {
  timeout: number;
  health?: SearchHealthConfig;
  engines: Record<string, SearchEngineConfig>;
}

// ============================================================================
// Agent Teams
// ============================================================================

/** Team configuration. */
export interface TeamConfig {
  /** Maximum concurrent tasks on the board (default: 50). */
  maxTasks: number;
  /** Message channel buffer size (default: 128). */
  channelBuffer: number;
  /** Maximum coordinator rounds before runUntilDone exits (default: 10). */
  maxRounds: number;
  /** Worker/Reviewer polling interval in milliseconds (default: 200). */
  pollIntervalMs: number;
}

/** A task snapshot from the team board (read-only). */
export interface TeamTask {
  id: string;
  description: string;
  postedBy: string;
  assignedTo: string | null;
  /** "open" | "in_progress" | "in_review" | "done" | "rejected" */
  status: string;
  result: string | null;
  createdAt: number;
  updatedAt: number;
}

/** Result returned by `TeamRunner.runUntilDone()`. */
export interface TeamRunResult {
  doneTasks: TeamTask[];
  rejectedTasks: TeamTask[];
  rounds: number;
}

/** Board stats object returned by `TeamTaskBoard.stats()`. */
export interface TeamBoardStats {
  open: number;
  inProgress: number;
  inReview: number;
  done: number;
  rejected: number;
  total: number;
}

/**
 * Shared task board for team coordination.
 *
 * Access via `Team.taskBoard()` or `TeamRunner.taskBoard()`.
 */
export declare class TeamTaskBoard {
  /**
   * Post a new task. Returns the task ID, or null if the board is full.
   * @param description - Task description
   * @param postedBy - Member ID posting the task
   * @param assignTo - Optional member ID to pre-assign the task
   */
  post(description: string, postedBy: string, assignTo?: string | null): string | null;

  /** Claim the next open or rejected task for a member. */
  claim(memberId: string): TeamTask | null;

  /** Mark a task as complete with a result. Returns true if found. */
  complete(taskId: string, result: string): boolean;

  /** Approve a task (reviewer action). Returns true if the task was in InReview state. */
  approve(taskId: string): boolean;

  /** Reject a task back to open (reviewer action). Returns true if found. */
  reject(taskId: string): boolean;

  /** Get a task by ID. */
  get(taskId: string): TeamTask | null;

  /**
   * Get all tasks with the given status.
   * @param status - "open" | "in_progress" | "in_review" | "done" | "rejected"
   */
  byStatus(status: string): TeamTask[];

  /** Get all tasks assigned to a member. */
  byAssignee(memberId: string): TeamTask[];

  /** Summary stats. */
  stats(): TeamBoardStats;

  /** Total number of tasks on the board. */
  readonly len: number;

  /** True if the board has no tasks. */
  readonly isEmpty: boolean;
}

/**
 * Multi-agent team coordinator.
 *
 * Create the team, add members, then pass it to `TeamRunner` to execute.
 *
 * @example
 * ```js
 * const team = new Team("refactor-auth");
 * team.addMember("lead", "lead");
 * team.addMember("worker-1", "worker");
 * team.addMember("reviewer", "reviewer");
 * const runner = new TeamRunner(team);
 * runner.bindSession("lead", leadSession);
 * const result = await runner.runUntilDone("Refactor auth");
 * ```
 */
export declare class Team {
  constructor(name: string, config?: TeamConfig);

  /**
   * Add a member to the team.
   * @param memberId - Unique member identifier
   * @param role - "lead" | "worker" | "reviewer"
   */
  addMember(memberId: string, role: string): void;

  /** Remove a member. Returns true if found. */
  removeMember(memberId: string): boolean;

  /** Number of registered members. */
  readonly memberCount: number;

  /** Get the shared task board for inspection. */
  taskBoard(): TeamTaskBoard;
}

/**
 * Binds an agent team to real `Session` executors and runs the workflow.
 *
 * The team is consumed on construction.
 *
 * @example
 * ```js
 * const runner = new TeamRunner(team);
 * runner.bindSession("lead", agent.session("."));
 * runner.bindSession("worker-1", agent.session("."));
 * runner.bindSession("reviewer", agent.session("."));
 * const result = await runner.runUntilDone("Build the feature");
 * for (const task of result.doneTasks) {
 *   console.log(task.id, task.result);
 * }
 * ```
 */
export declare class TeamRunner {
  /**
   * Create a runner from a team. The team is consumed.
   * @param team - The team to run (consumed; further use throws)
   */
  constructor(team: Team);

  /**
   * Bind a `Session` to a team member.
   * @param memberId - Must match a member added to the team
   * @param session - A `Session` from `Agent.session()`
   */
  bindSession(memberId: string, session: Session): void;

  /** Get the shared task board for inspection. */
  taskBoard(): TeamTaskBoard;

  /**
   * Run the Lead → Worker → Reviewer workflow until all tasks are done.
   *
   * 1. Lead decomposes `goal` into tasks via JSON response.
   * 2. Workers concurrently claim and execute tasks.
   * 3. Reviewer approves or rejects completed tasks.
   * 4. Rejected tasks re-enter the queue for retry.
   *
   * @param goal - High-level goal to decompose and execute
   */
  runUntilDone(goal: string): Promise<TeamRunResult>;
}

// ============================================================================
// Agent
// ============================================================================

/**
 * AI coding agent. Create with `Agent.create()`, then call `agent.session()`.
 */
export declare class Agent {
  /**
   * Create an Agent from a config file path or inline config string.
   * @param configSource - Path to .hcl/.json file, or inline JSON/HCL string
   */
  static create(configSource: string): Promise<Agent>;

  /**
   * Bind to a workspace directory, returning a Session.
   * @param workspace - Path to the workspace directory
   * @param options - Optional session configuration
   */
  session(workspace: string, options?: SessionOptions): Session;

  /**
   * Resume a previously saved session by ID.
   * @param sessionId - The session ID to resume
   * @param sessionStoreDir - Directory where sessions are stored
   * @param options - Optional session overrides
   */
  resumeSession(sessionId: string, sessionStoreDir: string, options?: SessionOptions): Session;
}

// ============================================================================
// Session
// ============================================================================

/**
 * Workspace-bound session. All LLM and tool operations happen here.
 */
export declare class Session {
  /**
   * Send a prompt and wait for the complete response.
   * @param prompt - The prompt to send
   * @param history - Optional conversation history
   */
  send(prompt: string, history?: MessageObject[]): Promise<AgentResult>;

  /**
   * Send a prompt and get a streaming event iterator.
   * @param prompt - The prompt to send
   * @param history - Optional conversation history
   */
  stream(prompt: string, history?: MessageObject[]): Promise<EventStream>;

  /**
   * Send a prompt with image attachments.
   * @param prompt - The prompt to send
   * @param attachments - Array of `{ data: Buffer, mediaType: string }`
   * @param history - Optional conversation history
   */
  sendWithAttachments(
    prompt: string,
    attachments: AttachmentObject[],
    history?: MessageObject[]
  ): Promise<AgentResult>;

  /**
   * Stream a prompt with image attachments.
   */
  streamWithAttachments(
    prompt: string,
    attachments: AttachmentObject[],
    history?: MessageObject[]
  ): Promise<EventStream>;

  /** Return the session's conversation history. */
  history(): MessageObject[];

  /** Execute a tool by name, bypassing the LLM. */
  tool(name: string, args: unknown): Promise<ToolResult>;

  /** Read a file from the workspace. */
  readFile(path: string): Promise<string>;

  /** Execute a bash command in the workspace. */
  bash(command: string): Promise<string>;

  /** Search for files matching a glob pattern. */
  glob(pattern: string): Promise<string[]>;

  /** Search file contents with a regex pattern. */
  grep(pattern: string): Promise<string>;

  // --- Queue API ---

  /** Check if this session has a lane queue configured. */
  hasQueue(): boolean;

  /**
   * Configure a lane's handler mode.
   * @param lane - "control" | "query" | "execute" | "generate"
   * @param config - `{ mode: "internal" | "external" | "hybrid", timeoutMs?: number }`
   */
  setLaneHandler(lane: string, config: LaneHandlerConfig): Promise<void>;

  /**
   * Complete an external task by ID.
   * @returns true if found, false if not found
   */
  completeExternalTask(taskId: string, result: ExternalTaskResult): Promise<boolean>;

  /** Get pending external tasks. */
  pendingExternalTasks(): Promise<unknown>;

  /** Get queue statistics. */
  queueStats(): Promise<QueueStats>;

  /** Get dead letters from the DLQ. */
  deadLetters(): Promise<unknown>;

  // --- Hook API ---

  /**
   * Register a hook for lifecycle event interception.
   * @param hookId - Unique hook identifier
   * @param eventType - Event type (e.g. "pre_tool_use", "post_tool_use")
   * @param matcher - Optional filter
   * @param config - Optional config (priority, timeoutMs, etc.)
   */
  registerHook(
    hookId: string,
    eventType: string,
    matcher?: HookMatcherObject,
    config?: HookConfigObject
  ): void;

  /**
   * Unregister a hook by ID.
   * @returns true if found and removed
   */
  unregisterHook(hookId: string): boolean;

  /** Number of registered hooks. */
  hookCount(): number;

  // --- Session Metadata ---

  readonly sessionId: string;
  readonly workspace: string;
  readonly initWarning: string | null;

  // --- Session Persistence ---

  /** Save the session to the configured store. */
  save(): Promise<void>;

  // --- Memory API ---

  readonly hasMemory: boolean;

  /** Remember a successful task execution. */
  rememberSuccess(task: string, tools: string[], result: string): Promise<void>;

  /** Remember a failed task execution. */
  rememberFailure(task: string, error: string, tools: string[]): Promise<void>;

  /**
   * Recall memories similar to a query.
   * @param query - Search query
   * @param limit - Maximum number of results (default: 5)
   */
  recallSimilar(query: string, limit?: number): Promise<unknown>;

  /**
   * Recall memories by tags.
   * @param tags - Tags to search for
   * @param limit - Maximum number of results (default: 10)
   */
  recallByTags(tags: string[], limit?: number): Promise<unknown>;

  /**
   * Get recent memory items.
   * @param limit - Maximum number of results (default: 10)
   */
  memoryRecent(limit?: number): Promise<unknown>;

  /** Get memory statistics. */
  memoryStats(): Promise<unknown>;
}

// ============================================================================
// Functions
// ============================================================================

/** Return a list of built-in skills compiled into the library. */
export declare function builtinSkills(): SkillInfo[];
