"""
A3S Code Agent Python SDK

A Python client for the A3S Code Agent gRPC service.
"""

from .client import A3sClient
from .types import (
    # Enums
    HealthStatus,
    HealthStatusCode,
    SessionState,
    MessageRole,
    FinishReason,
    ChunkType,
    EventType,
    SessionLane,
    TimeoutAction,
    TaskHandlerMode,
    PermissionDecision,
    Complexity,
    StepStatus,
    MemoryType,
    CronJobStatus,
    CronExecutionStatus,
    StorageType,
    AgenticStrategy,
    # Types
    AgentInfo,
    ToolCapability,
    ModelCapability,
    ResourceLimits,
    LLMConfig,
    SessionConfig,
    ContextUsage,
    Session,
    Message,
    TextContent,
    ToolUseContent,
    ToolResultContent,
    ContentBlock,
    ConversationMessage,
    ToolResult,
    ToolCall,
    Usage,
    GenerateResponse,
    GenerateChunk,
    Skill,
    AgentEvent,
    ConfirmationPolicy,
    LaneHandlerConfig,
    ExternalTask,
    PermissionRule,
    PermissionPolicy,
    Todo,
    # Provider types
    ModelCostInfo,
    ModelLimitInfo,
    ModelModalitiesInfo,
    ModelInfo,
    ProviderInfo,
    # Planning types
    PlanStep,
    ExecutionPlan,
    AgentGoal,
    # Memory types
    MemoryItem,
    MemoryStats,
    # MCP types
    McpStdioTransport,
    McpHttpTransport,
    McpTransport,
    McpServerConfig,
    McpServerInfo,
    McpToolInfo,
    # Cron types
    CronJob,
    CronExecution,
    # Agentic types
    AgenticStep,
    AgenticGenerateResponse,
    AgenticGenerateEvent,
    # Delegation types
    DelegateResponse,
    # Queue types
    LaneStats,
    QueueStats,
)

__version__ = "0.4.1"
__all__ = [
    "A3sClient",
    # Enums
    "HealthStatus",
    "HealthStatusCode",
    "SessionState",
    "MessageRole",
    "FinishReason",
    "ChunkType",
    "EventType",
    "SessionLane",
    "TimeoutAction",
    "TaskHandlerMode",
    "PermissionDecision",
    "Complexity",
    "StepStatus",
    "MemoryType",
    "CronJobStatus",
    "CronExecutionStatus",
    "StorageType",
    "AgenticStrategy",
    # Types
    "AgentInfo",
    "ToolCapability",
    "ModelCapability",
    "ResourceLimits",
    "LLMConfig",
    "SessionConfig",
    "ContextUsage",
    "Session",
    "Message",
    "TextContent",
    "ToolUseContent",
    "ToolResultContent",
    "ContentBlock",
    "ConversationMessage",
    "ToolResult",
    "ToolCall",
    "Usage",
    "GenerateResponse",
    "GenerateChunk",
    "Skill",
    "AgentEvent",
    "ConfirmationPolicy",
    "LaneHandlerConfig",
    "ExternalTask",
    "PermissionRule",
    "PermissionPolicy",
    "Todo",
    # Provider types
    "ModelCostInfo",
    "ModelLimitInfo",
    "ModelModalitiesInfo",
    "ModelInfo",
    "ProviderInfo",
    # Planning types
    "PlanStep",
    "ExecutionPlan",
    "AgentGoal",
    # Memory types
    "MemoryItem",
    "MemoryStats",
    # MCP types
    "McpStdioTransport",
    "McpHttpTransport",
    "McpTransport",
    "McpServerConfig",
    "McpServerInfo",
    "McpToolInfo",
    # Cron types
    "CronJob",
    "CronExecution",
    # Agentic types
    "AgenticStep",
    "AgenticGenerateResponse",
    "AgenticGenerateEvent",
    # Delegation types
    "DelegateResponse",
    # Queue types
    "LaneStats",
    "QueueStats",
]
