"""Stable error codes attached to exceptions raised by the native core."""

from typing import Literal

CodeErrorCode = Literal[
    "CONFIG_ERROR",
    "LLM_ERROR",
    "TOOL_ERROR",
    "SESSION_ERROR",
    "SESSION_CONFIGURATION_ERROR",
    "SESSION_INITIALIZATION_ERROR",
    "ASYNC_SESSION_BUILD_REQUIRED",
    "SESSION_CLOSED",
    "SESSION_BUSY",
    "RUN_IDENTITY_CONFLICT",
    "TASK_ADMISSION_CANCELLED",
    "TASK_SCHEDULER_CLOSED",
    "BUDGET_EXHAUSTED",
    "SERVE_STARTUP_FAILED",
    "SERVE_RUNTIME_FAILED",
    "SERVE_DAEMON_PANICKED",
    "SERVE_SHUTDOWN_DEADLINE_EXCEEDED",
    "SECURITY_ERROR",
    "CONTEXT_ERROR",
    "MCP_ERROR",
    "QUEUE_ERROR",
    "IO_ERROR",
    "SERIALIZATION_ERROR",
    "INTERNAL_ERROR",
]

__all__ = ["CodeErrorCode"]
