export const copy = {
  zh: {
    eyebrow: 'OPEN SOURCE · EMBEDDABLE AGENT RUNTIME',
    titleLead: '把 A3S Code',
    titleAccent: '接进现有产品',
    subtitle:
      'A3S Code 8 提供受治理的 Agent 会话、异步工作区检索、Moli 无头搜索、模型边界证据、事件流和任务恢复。可以直接运行 a3s code，也可以通过 Rust、Node.js、Python 或 Go SDK 嵌入现有应用。',
    docs: '开始使用',
    github: '查看 GitHub',
    copy: '复制',
    copied: '已复制',
    installTabs: '选择安装平台',
    turn: '一次 Agent 执行会经过什么',
    proposal: '模型请求调用工具',
    governed: '执行前检查',
    result: '执行结果写入事件记录',
    context: '项目上下文 + 记忆',
    model: '模型',
    guard: '参数 → 权限 → 确认 → 预算 → 沙箱',
    evidence: 'Run · Trace · Artifact · Snapshot',
    record: '执行记录',
    surfacesLabel: '五种接入方式，同一套 Runtime',
    whyEyebrow: 'WHY A3S CODE',
    whyTitle: '工具执行之前，先检查参数、权限和确认状态',
    whyBody:
      '模型给出的工具调用不会直接落到文件系统或 Shell。Runtime 先完成检查，再把执行事件和结果交给应用。',
    architectureEyebrow: 'HOW IT RUNS',
    architectureTitle: '用 Python 走完一次执行',
    architectureBody:
      '示例使用仓库中实际提供的 a3s_code API。滚动或点击步骤，代码会逐步加入 Session、上下文限制、权限、事件流和持久化。',
    architectureAlt:
      'A3S Code 一次执行的交互流程图，展示任务规划、进度追踪、并行子智能体、报告制品和 RemoteUI 渐进式界面。',
    capabilitiesEyebrow: 'WHAT YOU GET',
    capabilitiesTitle: 'Runtime 提供的五类能力',
    capabilitiesBody:
      '工具、模型、任务记录、扩展接口和 Workspace 检索各自独立。语义检索由宿主主动开启；基础搜索不依赖 Embedding、Rerank 模型或向量数据库。',
    surfacesEyebrow: 'USE IT YOUR WAY',
    surfacesTitle: '直接运行 CLI，或使用四种 SDK',
    surfacesBody:
      '终端版用于直接操作项目；Rust crate、Node.js 包、Python 包和 Go module 用于 IDE、Runner、服务端或自有界面。',
    boundariesEyebrow: 'WHAT STAYS YOURS',
    boundariesTitle: 'Runtime 负责执行；应用负责账号、凭据和界面',
    boundaryItems: [
      'A3S Code Core 提供 Agent Runtime，不提供托管服务，也不规定界面应该长什么样。',
      'a3s code 的终端界面由独立的 A3S CLI 提供。',
      '账号、凭据、部署方式，以及哪些应用工具可以直接调用，仍由你的应用决定。',
    ],
    boundaryLink: '查看架构说明',
    boundaryCoreLabel: 'A3S CODE',
    boundaryCoreRole: '执行 Agent 与工具',
    boundaryContract: 'API 与事件',
    boundaryHostLabel: '你的应用',
    boundaryHostRole: '账号、权限与界面',
    stackTitle: 'TUI 生命周期',
    stackHint: '点击阶段查看过程',
    stackHintMobile: '点击步骤展开',
    stackTop: '产品',
    stackBottom: '记录',
    flowTask: '不联网检查这个仓库的发布风险，并生成报告',
    flowReplay: '重播',
    flowPlayOnce: '播放一次',
    tuiWorkspace: '~/workspace/a3s',
    tuiMode: 'default',
    tuiSlashInput: '/effort',
    tuiSlashEffort: '调整推理强度',
    tuiSlashModel: '切换模型与 Provider',
    tuiSlashTheme: '选择终端主题',
    tuiMentionInput: '检查 @AGENTS.md',
    tuiFilePicker: '@ file · ↑/↓ · →/← folder · Enter · Esc',
    tuiFileInstructions: '项目指令',
    tuiFileManifest: 'Rust workspace',
    tuiFileWebsite: '文档应用',
    tuiShellInput: 'cargo test -p a3s-code-core',
    tuiResearchInput: '调研 A3S Code 最新发布与兼容性变化',
    tuiUser: 'You',
    tuiWorking: 'Working…',
    tuiPlan: 'Plan',
    tuiPlanInspect: '读取项目约束与发布配置',
    tuiPlanDelegate: '并行检查代码、测试与文档',
    tuiPlanPublish: '生成报告制品并打开 RemoteUI',
    tuiSubagents: 'Subagents',
    tuiParallelTask: '并行检查发布风险',
    tuiAgentExploreTask: '扫描约束与发布工作流',
    tuiAgentTestTask: '运行核心回归测试',
    tuiAgentReviewTask: '核对文档与包元数据',
    tuiArtifact: 'Artifact',
    tuiArtifactPath: 'release-risk-report/index.html',
    tuiArtifactWriting: 'publishing…',
    tuiArtifactReady: 'HTML · 18.4 KB',
    tuiOpenView: 'Open view',
    tuiRemoteUi: 'RemoteUI',
    tuiRemotePreparing: 'preparing',
    tuiRemoteStreaming: 'streaming',
    tuiRemoteReady: 'ready',
    tuiReportTitle: '发布风险报告',
    tuiReportSummary: '2 risks · 12 checks',
    tuiAssistant: 'A3S Code',
    tuiResponse:
      '检查完成。3 个子智能体并行完成；报告制品已生成，可通过 RemoteUI 打开。',
    tuiContext: 'ctx:12%',
    tutorialStep: '步骤',
    tutorialCode: '代码',
    tutorialLayers: '当前负责的层',
    tutorialScroll: '继续向下',
    ctaEyebrow: 'TRY IT',
    ctaTitle: '从一个只读任务开始',
    ctaBody:
      '安装 a3s code 后，在已有仓库里执行一次检查；需要嵌入时再选择 Rust、Node.js、Python 或 Go SDK。',
    ctaPrimary: '查看快速开始',
    ctaSecondary: '查看 API',
    footer:
      'MIT 开源 · Rust 编写 · 支持 Terminal / Rust / Node.js / Python / Go',
  },
  en: {
    eyebrow: 'OPEN SOURCE · EMBEDDABLE AGENT RUNTIME',
    titleLead: 'Add A3S Code',
    titleAccent: 'to an existing product',
    subtitle:
      'A3S Code 8 provides governed agent sessions, asynchronous workspace retrieval, Moli-powered headless search, model-bound evidence, event streaming, and task recovery. Run a3s code directly or embed the Rust, Node.js, Python, or Go SDK.',
    docs: 'Get started',
    github: 'View on GitHub',
    copy: 'Copy',
    copied: 'Copied',
    installTabs: 'Choose an install target',
    turn: 'What happens during one agent turn',
    proposal: 'The model requests a tool',
    governed: 'Checks before execution',
    result: 'The result enters the event stream',
    context: 'project context + memory',
    model: 'model',
    guard: 'arguments → permission → approval → budget → sandbox',
    evidence: 'Run · Trace · Artifact · Snapshot',
    record: 'run record',
    surfacesLabel: 'Five ways in, one runtime',
    whyEyebrow: 'WHY A3S CODE',
    whyTitle: 'Check arguments, permissions, and approvals before execution',
    whyBody:
      'Model tool calls do not go straight to the filesystem or shell. The runtime completes its checks first, then sends execution events and results to the application.',
    architectureEyebrow: 'HOW IT RUNS',
    architectureTitle: 'Follow one complete run in Python',
    architectureBody:
      'The example uses the actual a3s_code API in this repository. Scroll or select a step to add the Session, context limits, policy, event stream, and persistence.',
    architectureAlt:
      'An interactive A3S Code run showing task planning, progress tracking, parallel subagents, report artifacts, and a progressive RemoteUI view.',
    capabilitiesEyebrow: 'WHAT YOU GET',
    capabilitiesTitle: 'Five parts of the runtime',
    capabilitiesBody:
      'Tools, models, run data, extensions, and workspace retrieval are configured separately. The host opts into semantics; baseline search needs no embedding model, reranker model, or vector database.',
    surfacesEyebrow: 'USE IT YOUR WAY',
    surfacesTitle: 'Run the CLI or use one of four SDKs',
    surfacesBody:
      'Use the terminal app directly in a repository. Use the Rust crate, Node.js package, Python package, or Go module in an IDE, runner, server, or custom interface.',
    boundariesEyebrow: 'WHAT STAYS YOURS',
    boundariesTitle: 'The runtime executes; the app owns accounts and access',
    boundaryItems: [
      'A3S Code Core provides the agent runtime. It is not a hosted service and does not dictate your UI.',
      'The a3s code terminal interface comes from the separate A3S CLI.',
      'Accounts, credentials, deployment, and direct access to application tools remain under your control.',
    ],
    boundaryLink: 'Read the architecture guide',
    boundaryCoreLabel: 'A3S CODE',
    boundaryCoreRole: 'RUNS AGENTS + TOOLS',
    boundaryContract: 'APIs + EVENTS',
    boundaryHostLabel: 'YOUR APP',
    boundaryHostRole: 'OWNS UI + ACCESS',
    stackTitle: 'TUI lifecycle',
    stackHint: 'SELECT A PHASE TO INSPECT IT',
    stackHintMobile: 'TAP A STEP TO EXPAND',
    stackTop: 'PRODUCT',
    stackBottom: 'RECORDS',
    flowTask: 'Audit this repo for release risks offline; generate a report',
    flowReplay: 'REPLAY',
    flowPlayOnce: 'PLAY ONCE',
    tuiWorkspace: '~/workspace/a3s',
    tuiMode: 'default',
    tuiSlashInput: '/effort',
    tuiSlashEffort: 'adjust model effort',
    tuiSlashModel: 'switch model and provider',
    tuiSlashTheme: 'select the terminal theme',
    tuiMentionInput: 'Review @AGENTS.md',
    tuiFilePicker: '@ file · ↑/↓ · →/← folder · Enter · Esc',
    tuiFileInstructions: 'workspace instructions',
    tuiFileManifest: 'Rust workspace',
    tuiFileWebsite: 'documentation app',
    tuiShellInput: 'cargo test -p a3s-code-core',
    tuiResearchInput: 'Research the latest A3S Code releases and compatibility',
    tuiUser: 'You',
    tuiWorking: 'Working…',
    tuiPlan: 'Plan',
    tuiPlanInspect: 'Read repo constraints and release config',
    tuiPlanDelegate: 'Check code, tests, and docs in parallel',
    tuiPlanPublish: 'Publish report artifact and open RemoteUI',
    tuiSubagents: 'Subagents',
    tuiParallelTask: 'Audit release risks in parallel',
    tuiAgentExploreTask: 'Scan constraints and release workflows',
    tuiAgentTestTask: 'Run the core regression suite',
    tuiAgentReviewTask: 'Review docs and package metadata',
    tuiArtifact: 'Artifact',
    tuiArtifactPath: 'release-risk-report/index.html',
    tuiArtifactWriting: 'publishing…',
    tuiArtifactReady: 'HTML · 18.4 KB',
    tuiOpenView: 'Open view',
    tuiRemoteUi: 'RemoteUI',
    tuiRemotePreparing: 'preparing',
    tuiRemoteStreaming: 'streaming',
    tuiRemoteReady: 'ready',
    tuiReportTitle: 'Release risk report',
    tuiReportSummary: '2 risks · 12 checks',
    tuiAssistant: 'A3S Code',
    tuiResponse:
      'Review complete. Three subagents finished in parallel; the report artifact is ready to open in RemoteUI.',
    tuiContext: 'ctx:12%',
    tutorialStep: 'STEP',
    tutorialCode: 'CODE',
    tutorialLayers: 'ACTIVE LAYER',
    tutorialScroll: 'KEEP SCROLLING',
    ctaEyebrow: 'TRY IT',
    ctaTitle: 'Start with a read-only task',
    ctaBody:
      'Install a3s code and run one inspection in an existing repository. Choose the Rust, Node.js, Python, or Go SDK when you are ready to embed it.',
    ctaPrimary: 'Open the quick start',
    ctaSecondary: 'Open the API reference',
    footer:
      'MIT licensed · Built in Rust · Terminal / Rust / Node.js / Python / Go',
  },
};

export type HomeLabels = (typeof copy)[keyof typeof copy];
