export const copy = {
  zh: {
    eyebrow: '开源 · 可嵌入的 Agent Runtime',
    titleLead: '把 A3S Code',
    titleAccent: '接进现有产品',
    subtitle:
      '跑编码 Agent 时，工具调用先过权限再执行；会话能保存、能恢复。默认配置够用，复杂能力按需打开。终端直接跑 a3s code，或用 Rust / Node.js / Python / Go SDK 嵌进你的产品。',
    docs: '开始使用',
    github: '查看 GitHub',
    copy: '复制',
    copied: '已复制',
    installTabs: '选择安装平台',
    turn: '一次 Agent 执行会经过什么',
    proposal: '模型请求调用工具',
    governed: '执行前检查',
    result: '执行结果写入事件记录',
    context: '项目上下文 + 记忆',
    model: '模型',
    guard: '参数 → 权限 → 确认 → 预算 → 沙箱',
    evidence: 'Run · Trace · Artifact · Snapshot',
    record: '执行记录',
    surfacesLabel: '五种入口，同一套 Runtime',
    whyEyebrow: 'WHY A3S CODE',
    whyTitle: '模型想动文件或跑 Shell 时，先过你的规则',
    whyBody:
      '工具参数不会直接落地。Runtime 先做参数、权限和确认检查，再执行，并把过程事件回给你的应用。',
    architectureEyebrow: 'HOW IT RUNS',
    architectureTitle: '用 Python 看完一次完整调用',
    architectureBody:
      '下面的例子就是仓库里的 a3s_code API。点步骤，看 Session、权限、事件流和持久化是怎么加上去的。',
    architectureAlt:
      '一次 A3S Code 执行的示意：规划、进度、子 Agent、报告和 RemoteUI。',
    capabilitiesEyebrow: 'WHAT YOU GET',
    capabilitiesTitle: 'Runtime 本身提供什么',
    capabilitiesBody:
      '默认不带 Advanced 评估、server 和无头搜索。基础搜索不需要 Embedding 或向量库；语义检索由你的应用自己打开。',
    surfacesEyebrow: 'USE IT YOUR WAY',
    surfacesTitle: '终端直接跑，或嵌进四种 SDK',
    surfacesBody:
      '在仓库里用 a3s code；要做 IDE、Runner 或自有界面，用 Rust / Node.js / Python / Go。',
    boundariesEyebrow: 'WHAT STAYS YOURS',
    boundariesTitle: 'Runtime 管执行；账号和界面归你',
    boundaryItems: [
      'Core 只提供 Agent Runtime，不是托管服务，也不规定 UI。',
      '终端界面来自独立的 A3S CLI。',
      '账号、凭据、部署，以及哪些业务工具能直接调，都由你的应用决定。',
    ],
    boundaryLink: '查看架构说明',
    boundaryCoreLabel: 'A3S CODE',
    boundaryCoreRole: '执行 Agent 与工具',
    boundaryContract: 'API 与事件',
    boundaryHostLabel: '你的应用',
    boundaryHostRole: '账号、权限与界面',
    stackTitle: 'TUI 生命周期',
    stackHint: '点击阶段查看过程',
    stackHintMobile: '点击步骤展开',
    stackTop: '产品',
    stackBottom: '记录',
    flowTask: '不联网检查这个仓库的发布风险，并生成报告',
    flowReplay: '重播',
    flowPlayOnce: '播放一次',
    tuiWorkspace: '~/workspace/a3s',
    tuiMode: 'default',
    tuiSlashInput: '/effort',
    tuiSlashEffort: '调整推理强度',
    tuiSlashModel: '切换模型与 Provider',
    tuiSlashTheme: '选择终端主题',
    tuiMentionInput: '检查 @AGENTS.md',
    tuiFilePicker: '@ file · ↑/↓ · →/← folder · Enter · Esc',
    tuiFileInstructions: '项目指令',
    tuiFileManifest: 'Rust workspace',
    tuiFileWebsite: '文档应用',
    tuiShellInput: 'cargo test -p a3s-code-core',
    tuiResearchInput: '调研 A3S Code 最新发布与兼容性变化',
    tuiUser: 'You',
    tuiWorking: 'Working…',
    tuiPlan: 'Plan',
    tuiPlanInspect: '读取项目约束与发布配置',
    tuiPlanDelegate: '并行检查代码、测试与文档',
    tuiPlanPublish: '生成报告制品并打开 RemoteUI',
    tuiSubagents: 'Subagents',
    tuiParallelTask: '并行检查发布风险',
    tuiAgentExploreTask: '扫描约束与发布工作流',
    tuiAgentTestTask: '运行核心回归测试',
    tuiAgentReviewTask: '核对文档与包元数据',
    tuiArtifact: 'Artifact',
    tuiArtifactPath: 'release-risk-report/index.html',
    tuiArtifactWriting: 'publishing…',
    tuiArtifactReady: 'HTML · 18.4 KB',
    tuiOpenView: 'Open view',
    tuiRemoteUi: 'RemoteUI',
    tuiRemotePreparing: 'preparing',
    tuiRemoteStreaming: 'streaming',
    tuiRemoteReady: 'ready',
    tuiReportTitle: '发布风险报告',
    tuiReportSummary: '2 risks · 12 checks',
    tuiAssistant: 'A3S Code',
    tuiResponse:
      '检查完成。3 个子智能体并行完成；报告制品已生成，可通过 RemoteUI 打开。',
    tuiContext: 'ctx:12%',
    tutorialStep: '步骤',
    tutorialCode: '代码',
    tutorialLayers: '当前负责的层',
    tutorialScroll: '继续向下',
    ctaEyebrow: 'TRY IT',
    ctaTitle: '先在已有仓库里跑一次',
    ctaBody:
      '装好 a3s code，找个项目试一下。要嵌进产品时，再选 Rust、Node.js、Python 或 Go。',
    ctaPrimary: '查看快速开始',
    ctaSecondary: '查看 API',
    footer: 'MIT · 用 Rust 写的 · Terminal / Rust / Node.js / Python / Go',
  },
  en: {
    eyebrow: 'Open source · embeddable agent runtime',
    titleLead: 'Add A3S Code',
    titleAccent: 'to an existing product',
    subtitle:
      'A coding-agent runtime that checks tools before they run, keeps sessions recoverable, and stays small by default. Run a3s code in a repo, or embed the Rust, Node.js, Python, or Go SDK.',
    docs: 'Get started',
    github: 'View on GitHub',
    copy: 'Copy',
    copied: 'Copied',
    installTabs: 'Choose an install target',
    turn: 'What happens during one agent turn',
    proposal: 'The model requests a tool',
    governed: 'Checks before execution',
    result: 'The result enters the event stream',
    context: 'project context + memory',
    model: 'model',
    guard: 'arguments → permission → approval → budget → sandbox',
    evidence: 'Run · Trace · Artifact · Snapshot',
    record: 'run record',
    surfacesLabel: 'Five entry points, one runtime',
    whyEyebrow: 'WHY A3S CODE',
    whyTitle: 'Tool calls hit your rules before the filesystem or shell',
    whyBody:
      'The model cannot touch files or run commands until the runtime checks arguments, permissions, and approvals. Then it executes and streams events back to your app.',
    architectureEyebrow: 'HOW IT RUNS',
    architectureTitle: 'Walk through one Python run',
    architectureBody:
      'This uses the real a3s_code API from the repo. Click the steps to see Session, policy, events, and persistence get added.',
    architectureAlt:
      'A sample A3S Code run: planning, progress, subagents, a report, and RemoteUI.',
    capabilitiesEyebrow: 'WHAT YOU GET',
    capabilitiesTitle: 'What the runtime ships with',
    capabilitiesBody:
      'Advanced evaluation, server, and headless search stay off unless you turn them on. Basic search does not need embeddings or a vector DB.',
    surfacesEyebrow: 'USE IT YOUR WAY',
    surfacesTitle: 'CLI in a repo, or four SDKs in your product',
    surfacesBody:
      'Run a3s code locally. For an IDE, runner, or your own UI, pick Rust, Node.js, Python, or Go.',
    boundariesEyebrow: 'WHAT STAYS YOURS',
    boundariesTitle: 'We run the agent; you own accounts and UI',
    boundaryItems: [
      'Core is an agent runtime, not a hosted service, and it does not dictate your UI.',
      'The terminal UI comes from the separate A3S CLI.',
      'Accounts, credentials, deployment, and which app tools are callable stay yours.',
    ],
    boundaryLink: 'Read the architecture guide',
    boundaryCoreLabel: 'A3S CODE',
    boundaryCoreRole: 'RUNS AGENTS + TOOLS',
    boundaryContract: 'APIs + EVENTS',
    boundaryHostLabel: 'YOUR APP',
    boundaryHostRole: 'OWNS UI + ACCESS',
    stackTitle: 'TUI lifecycle',
    stackHint: 'SELECT A PHASE TO INSPECT IT',
    stackHintMobile: 'TAP A STEP TO EXPAND',
    stackTop: 'PRODUCT',
    stackBottom: 'RECORDS',
    flowTask: 'Audit this repo for release risks offline; generate a report',
    flowReplay: 'REPLAY',
    flowPlayOnce: 'PLAY ONCE',
    tuiWorkspace: '~/workspace/a3s',
    tuiMode: 'default',
    tuiSlashInput: '/effort',
    tuiSlashEffort: 'adjust model effort',
    tuiSlashModel: 'switch model and provider',
    tuiSlashTheme: 'select the terminal theme',
    tuiMentionInput: 'Review @AGENTS.md',
    tuiFilePicker: '@ file · ↑/↓ · →/← folder · Enter · Esc',
    tuiFileInstructions: 'workspace instructions',
    tuiFileManifest: 'Rust workspace',
    tuiFileWebsite: 'documentation app',
    tuiShellInput: 'cargo test -p a3s-code-core',
    tuiResearchInput: 'Research the latest A3S Code releases and compatibility',
    tuiUser: 'You',
    tuiWorking: 'Working…',
    tuiPlan: 'Plan',
    tuiPlanInspect: 'Read repo constraints and release config',
    tuiPlanDelegate: 'Check code, tests, and docs in parallel',
    tuiPlanPublish: 'Publish report artifact and open RemoteUI',
    tuiSubagents: 'Subagents',
    tuiParallelTask: 'Audit release risks in parallel',
    tuiAgentExploreTask: 'Scan constraints and release workflows',
    tuiAgentTestTask: 'Run the core regression suite',
    tuiAgentReviewTask: 'Review docs and package metadata',
    tuiArtifact: 'Artifact',
    tuiArtifactPath: 'release-risk-report/index.html',
    tuiArtifactWriting: 'publishing…',
    tuiArtifactReady: 'HTML · 18.4 KB',
    tuiOpenView: 'Open view',
    tuiRemoteUi: 'RemoteUI',
    tuiRemotePreparing: 'preparing',
    tuiRemoteStreaming: 'streaming',
    tuiRemoteReady: 'ready',
    tuiReportTitle: 'Release risk report',
    tuiReportSummary: '2 risks · 12 checks',
    tuiAssistant: 'A3S Code',
    tuiResponse:
      'Review complete. Three subagents finished in parallel; the report artifact is ready to open in RemoteUI.',
    tuiContext: 'ctx:12%',
    tutorialStep: 'STEP',
    tutorialCode: 'CODE',
    tutorialLayers: 'ACTIVE LAYER',
    tutorialScroll: 'KEEP SCROLLING',
    ctaEyebrow: 'TRY IT',
    ctaTitle: 'Try it in a repo you already have',
    ctaBody:
      'Install a3s code and run it once. Embed later with Rust, Node.js, Python, or Go if you need to.',
    ctaPrimary: 'Open the quick start',
    ctaSecondary: 'Open the API reference',
    footer: 'MIT · built in Rust · Terminal / Rust / Node.js / Python / Go',
  },
};

export type HomeLabels = (typeof copy)[keyof typeof copy];
